### PR TITLE
ci: fix broken CLI binary copy step for NPM publish

### LINKED ISSUE #3804: 🐛 Nightly builds of @biomejs/cli-* don't publish CLI binary
It would appear that none of the published NPM packages for the v1.8.4 nightly builds of `@biomejs/cli-linux-x64` include the `biome` binary, which I imagine is probably the only reason this package is published at all.

- [@biomejs/cli-linux-x64@v1.8.4-nightly.d079e53 files](https://www.npmjs.com/package/@biomejs/cli-linux-x64/v/1.8.4-nightly.d079e53?activeTab=code)
- [@biomejs/cli-linux-x64@1.8.4-nightly.bd1d0c6 files](https://www.npmjs.com/package/@biomejs/cli-linux-x64/v/1.8.4-nightly.bd1d0c6?activeTab=code)
- [@biomejs/cli-linux-x64@1.8.4-nightly.a579bf7 files](https://www.npmjs.com/package/@biomejs/cli-linux-x64/v/1.8.4-nightly.a579bf7?activeTab=code)
- [@biomejs/cli-linux-x64@1.8.3 files](https://www.npmjs.com/package/@biomejs/cli-linux-x64/v/1.8.3?activeTab=code)
- [@biomejs/cli-linux-x64@1.7.4-nightly.125f34b files](https://www.npmjs.com/package/@biomejs/cli-linux-x64/v/1.7.4-nightly.125f34b?activeTab=code)

### What happened?

Run the following on any x86 linux host:

```
npx @biomejs/biome@nightly
```

This results in the following error, or similar: `Error: Cannot find module '@biomejs/cli-linux-x64/biome'`

### Expected result

It should work as normal.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by benjamincburns**
## Summary

Fixes #3804 - see that issue for discussion.

## Test Plan

I'm not sure that it's possible to validate conclusively that this fixes #3804 without privileged access to the repository, as it's part of the NPM publish workflow.

### CODE REVIEW

**Comment by dyc3** [comment]
Thanks for the PR! I've pinged the other maintainers about this so they can take a look before we release v1.9.0.

**Comment by benjamincburns** [comment]
Thanks, @dyc3! You won't be able to publish v1.9.0 successfully without a similar change to this one, so definitely worth addressing it prior to the release. 😅

Could I please also request that you guys publish another nightly after this merges? Unless v1.9.0 is expected to drop _imminently_, I'm currently blocked by the feature mentioned in biomejs/website#1058 not being available anywhere but in the (currently broken) nightly.

**Comment by Conaclos** [comment]
> Could I please also request that you guys publish another nightly after this merges?

I planned to release a nightly on Monday.
1.9 should be released within a week.

**Review by Conaclos — APPROVED** [review]
Thanks for the fix. Let's release a nightly as soon as this is merged.

**Comment by Conaclos** [comment]
Nightly published and working :)

**Pull request merged**
