### PR TITLE
draft: css module level 3 parser

### PR DESCRIPTION
**Pull request by suxin2017**
## Summary

A very rough draft implementation was implemented, all tests have passed, how would such a loose cst help us, which currently does not support nesting

### CODE REVIEW

**Comment by ematipico** [comment]
@suxin2017 could explain to us what exactly you implemented in this PR? 

I took a brief look at it, and it seems that you deleted a lot of stuff that was previously written, and also changed a lot the name of the nodes, for reasons that haven't been explained.

Maybe you opened this PR to get some feedback, but first you need to explain to us **what** you implemented (many things are already implemented), and explain your changes.

**Comment by suxin2017** [comment]
> @suxin2017 could explain to us what exactly you implemented in this PR?
> 
> I took a brief look at it, and it seems that you deleted a lot of stuff that was previously written, and also changed a lot the name of the nodes, for reasons that haven't been explained.
> 
> Maybe you opened this PR to get some feedback, but first you need to explain to us **what** you implemented (many things are already implemented), and explain your changes.

I want to implement our cst with the same syntax as css syntax 3, which was mixed
css syntax 3
https://www.w3.org/TR/css-syntax-3/#consume-list-of-rules
And css syntax 2.2
https://www.w3.org/TR/CSS22/grammar.html#grammar


Differences between css syntax 3 and css syntax 2
https://www.w3.org/TR/css-syntax-3/#changes-css21

I want to implement our cst exactly like css syntax 3

` ` `
// css syntax 2
stylesheet
: [ CHARSET_SYM STRING ';' ]?
[S|CDO|CDC]* [ import [ CDO S* | CDC S* ]* ]*
[ [ ruleset | media | page ] [ CDO S* | CDC S* ]* ]*
;
import
: IMPORT_SYM S*
[STRING|URI] S* media_list?  '; ' S*
;
media
: MEDIA_SYM S* media_list '{' S* ruleset* '}' S*
;
media_list
: medium [ COMMA S* medium]*
;
medium
: IDENT S*
;
page
: PAGE_SYM S* pseudo_page?
'{' S* declaration?  [ ';' S* declaration? ] * '}' S*
;
pseudo_page
: ':' IDENT S*
;
operator
: '/' S* | ',' S*
;
combinator
: '+' S*
| '&gt; ' S*
;
property
: IDENT S*
;
ruleset
: selector [ ',' S* selector ]*
'{' S* declaration?  [ ';' S* declaration? ] * '}' S*
;
selector
: simple_selector [ combinator selector | S+ [ combinator? selector ]? ] ?
;
simple_selector
: element_name [ HASH | class | attrib | pseudo ]*
| [ HASH | class | attrib | pseudo ]+
;
class
: '.' IDENT
;
element_name
: IDENT | '*'
;
attrib
: '[' S* IDENT S* [ [ '=' | INCLUDES | DASHMATCH ] S*
[ IDENT | STRING ] S* ]?  '] '
;
pseudo
: ':' [ IDENT | FUNCTION S* [IDENT S*]? ')' ]
;
declaration
: property ':' S* expr prio?
;
prio
: IMPORTANT_SYM S*
;
expr
: term [ operator? term ]*
;
term
: [ NUMBER S* | PERCENTAGE S* | LENGTH S* | EMS S* | EXS S* | ANGLE S* |
TIME S* | FREQ S* ]
| STRING S* | IDENT S* | URI S* | hexcolor | function
;
function
: FUNCTION S* expr ')' S*
;
/ *
* There is a constraint on the color that it must
* have either 3 or 6 hex-digits (i.e., [0-9a-fA-F])
* after the "#";  e.g., "#000" is OK, but "#abcd" is not.
* /
hexcolor
: HASH S*
;

` ` `

// css syntax 3
 
image

**Comment by ematipico** [comment]
Thank you for the detailed explanation @suxin2017 !

The issue I find with CSS syntax 3 parsing is that it doesn't help us very much in the analyzer, because most of important information needs to be preserved as is which is very generic, and it doesn't actually explain what's the meaning. Regardless, keeping the info as is doesn't leave much room of movement inside the analyzer, because everything is kept as it was (a string maybe?) And we can't analyse it very well.

It's also very confusing because other parts of the specs explain a different parsing logic, for example `@keyframe`, where even the block section has specific parsing rules and errors.

I tend to follow the specific parsing rules, because they have better error rules, and we can create better nodes during the parsing phase .

**Comment by suxin2017** [comment]
> Thank you for the detailed explanation @suxin2017 !
> 
> The issue I find with CSS syntax 3 parsing is that it doesn't help us very much in the analyzer, because most of important information needs to be preserved as is which is very generic, and it doesn't actually explain what's the meaning. Regardless, keeping the info as is doesn't leave much room of movement inside the analyzer, because everything is kept as it was (a string maybe?) And we can't analyse it very well.
> 
> That's the biggest difect of PostCSS. They kept most every as it is, they don't even parse it. This results in lint rules that should be caught by the parser instead an analyzer. The analyzer needs to do a bunch of string manipulation and regex checks.
> 
> It's also very confusing because other parts of the specs explain a different parsing logic, for example `@keyframe`, where even the block section has specific parsing rules and errors.
> 
> I tend to follow the specific parsing rules, because they have better error rules, and we can create better nodes during the parsing phase .

Ok, thank you for your response,

**Pull request closed without merging**
