### PR TITLE
docs(website): add third-party tool in continuous integration section

### PR DESCRIPTION
**Pull request by mongolyy**
## Summary

I have created github actions that work with [reviewdog](https://github.com/reviewdog/reviewdog) to utilize the pull request commenting and commit suggestion functionality.

https://github.com/marketplace/actions/run-biome-with-reviewdog
https://github.com/mongolyy/reviewdog-action-biome

I believe this action will improve the usability of the combination of biome and github actions.

## Test Plan

Check the [deployment preview](https://deploy-preview-1585--biomejs.netlify.app/recipes/continuous-integration/).

### CODE REVIEW

**Comment by mongolyy** [comment]
I have created a pull request, but if you would like to create an issue or discussion to discuss it, please let me know.

**Comment by ematipico** [comment]
Can you give us more context? What does this action do **more** than Biome? The `ci` command already supports annotations on GitHub

**Comment by mongolyy** [comment]
Thanks for the response.

With annotation, the pull request is just commented and we have to open the IDE, github.dev, etc. to fix it.
I thought it would be useful to be able to modify the remarks from Biome with a few clicks on the github pull request screen.

See the sample pull request.
https://github.com/mongolyy/reviewdog-action-biome/pull/27

I made it so that commit suggestions are made based on the results of `biome check --apply`.
Of course, if something can't be safe fixed, it will be commented in the pull request.

I think this will make it easier for developers to fix things that are pointed out by biome.

Sorry if this is not in line with the intention of the biome development team.
In that case, I will close this pull request.

**Comment by ematipico** [comment]
That's actually pretty neat! Amazing tool indeed! I'm happy to integrate it in our docs

**Comment by mongolyy** [comment]
Thank you. I am glad to hear you say so.
I am also happy to contribute to Biome.

I will continue to support Biome.

**Pull request merged**
