### PR TITLE
feat(biome_js_parser): forbid undefined as type name

### PR DESCRIPTION
**Pull request by fireairforce**
## Summary

closes: #3121

### CODE REVIEW

**Comment by Conaclos** [comment]
@ematipico Do you think this could be considered as a fix?

**Comment by ematipico** [comment]
Definitely a fix, yes

**Review by Conaclos — APPROVED** [review]
@fireairforce 
Looks good to me! Could you add a changelog entry under `## parser ### Bug fixes`?

**Comment by fireairforce** [comment]
done, sorry i forget changelog again.

**Pull request merged**
