### PR TITLE
refactor: warn clippy::trivially_copy_pass_by_ref

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

This enables the following clippy rule:
- [trivially_copy_pass_by_ref](https://rust-lang.github.io/rust-clippy/master/#/trivially_copy_pass_by_ref) that ensures that copyable small types are passed by value.

The idea of the rule is to prevent the use of a reference for a small copyable type. These types can generally be passed via a register instead of the stack.

I also set the `trivial-copy-size-limit` option to `4` bytes to avoid warning against 8 byte copyable types. If we removes existing references to its types, we observe a regression.   

## Test Plan

`cargo test`, `just lint`, `cargo build`, `just codegen`.

### CODE REVIEW

**Comment by ematipico** [comment]
!bench_formatter

**Comment by ematipico** [comment]
Could you please check how much memory the formatter uses before/after this change?

**Comment by Conaclos** [comment]
!bench_formatter

**Comment by Conaclos** [comment]
!bench_formatter

**Comment by Conaclos** [comment]
@ematipico I finally identified the issue regarding the regression: I removed references to a 8 bytes copyable type (TextRange). To avoid to warn against this type I set `trivial-copy-size-limit option` to 4 bytes. According to the last benchmark, it is a little better with the change (except for `formatter/canada.json`).

**Comment by Conaclos** [comment]
!bench_formatter

**Review by ematipico — COMMENTED** [review]
Here's the main question: when must we use `Copy`? 

This rule leverages the use of `Copy`, so when do we need to use this trait?

**Comment by Conaclos** [comment]
> This rule leverages the use of Copy, so when do we need to use this trait?

[trivially_copy_pass_by_ref](https://rust-lang.github.io/rust-clippy/master/#/trivially_copy_pass_by_ref) reports copyable values passed by reference when the type uses less than `trivial-copy-size-limit`. By default, `trivial-copy-size-limit` is set to `8` bytes. Based on benchmarks, It seems that copying types like `TextRange` (`8` bytes sized) produced a perf regression. Thus, I set the limit to `trivial-copy-size-limit`.

Note that the rule **does not require a type that uses 4 bytes or less to be copyable**.

I am still a bit confused, because a lot of types are 8 bytes sized (u64, f64, ...), and even bigger (`Vec` is 3 words length). This is a bit strange that copying a TextRange lead to a perf regression...

I previously enabled [large_types_passed_by_value](https://rust-lang.github.io/rust-clippy/master/#/large_types_passed_by_value) that warns against "values" passed by value when their type use more than `pass-by-value-size-limit`. `pass-by-value-size-limit` is set to `256` bytes` by default. We had no instance of that. I think we could reduce the limit, the default seems very large. I think that most copyable types should be at most `24` bytes (`192` bits). A "good" limit could be 32 bytes.

If I set the limit to `24` in our code base, two warnings are emitted for values passed by values with the following types: 
- `BorrowedSourceCode` 32 bytes
- `Location` 72 bytes

It could be worth to investigate the cost of passing `Location` by value. 

To answer to your question, I think all types that use `4` bytes or less should be copyable. I think that copyable types that use more than `32` bytes should be avoided. For types that use between `4` and `32` bytes it is difficult to say.

**Comment by ematipico** [comment]
Given the explanation, I don't think it's worth adding this rule.

**Comment by Conaclos** [comment]
I would like to keep the PR open for now.

> Given the explanation, I don't think it's worth adding this rule.

Do you think the code change is still worth to merge?

**Comment by ematipico** [comment]
Personally, I'm more keen to use Clone over Copy. I like more explicit code over implicit code. Using clone shows intent and helps to craft better function signatures. &Self and self are very different signatures, but Copy makes everything different unless you're very good at documenting.

**Pull request closed without merging**
