### PR TITLE
fix: cargo build for publishing

### PR DESCRIPTION
**Pull request by nissy-dev**
## Summary

In 1.3.0 release, we tried to publish crates but it failed. This is because all crate versions were not upgraded to the same version at once.

So, I upgraded all crate versions to `0.3.0`. In 1.4.0 release, crate publishing should be successful.  I also added a note about this in the CONTRIBUTION.md.

## Test Plan

I'll try to publish crates in 1.4.0 release.

### CODE REVIEW

**Comment by ematipico** [comment]
Can you update the instructions too? It wasn't clear that ALL the crates must be updated. Last time I updated only the ones that were modified.

**Comment by nissy-dev** [comment]
> Can you update the instructions too? It wasn't clear that ALL the crates must be updated. Last time I updated only the ones that were modified.

I updated the releasing section in CONTRIBUTING.md.

**Review by ematipico — APPROVED** [review]

**Comment by ematipico** [comment]
https://github.com/biomejs/biome/actions/runs/6995453142/job/19030321019#step:4:1

It failed :(

**Comment by nissy-dev** [comment]
Thanks for checking. I created the follow-up PR #891

**Pull request merged**
