### PR TITLE
feat(cli): output report to file

### PR DESCRIPTION
**Pull request by Marcellofabrizio**
## Summary

Adds a CLI option to output a `json-pretty` report to a given file, similar to ESLint [output option](https://eslint.org/docs/latest/use/command-line-interface#output). I would really appreciate any sugestion on how to improve this.

## Test Plan

Run `biome lint --reporter=json-pretty --report-output-file=report.json` . The JSON file should contain the Report that was genereated

### CODE REVIEW

**Review by muriloarelhano — APPROVED** [review]

**Comment by muriloarelhano** [comment]
having the same issue here.

**Comment by dyc3** [comment]
What's the advantage of having this instead of just piping the output to a file? eg `biome lint --reporter=json-pretty > report.json`

**Comment by Marcellofabrizio** [comment]
> What's the advantage of having this instead of just piping the output to a file? eg `biome lint --reporter=json-pretty > report.json`

I think it would be usefull in cases with the following config on a `package.json`:
```
{
  "name": "app",
  "version": "1.0.0",
  "scripts": {
    "lint": "biome lint ./src",
    "lint:fix": "npm run lint -- check --write",
    "lint:report": "npm run lint -- --reporter=json > ./lint-report.json", 
}
```
Doing this would cause the `lint-report.json` file to have two extra lines on it, like:

```
> app@1.0.0 lint
> biome lint ./src --reporter=json
```
and this would break any JSON parsing, and this is troubling especially in deployment pipelines.

**Comment by Conaclos** [comment]
@Marcellofabrizio Are you going to use this option?

**Comment by Marcellofabrizio** [comment]
> @Marcellofabrizio Are you going to use this option?

Yes, I would. I think it's far cleaner than passing the result using `>`. But that's imo.

It would also be my first contribution 😄

**Comment by ematipico** [comment]
Thank you @Marcellofabrizio for your first contribution.

Could you please create an issue first? You can use the one that starts with a 📎

Make sure to describe the new feature. I will assign that to you.

While you create the issue, make sure to describe the business logic of the feature, and answer to these questions, they should help to write the business logic:
- should this option work without reporters? If not, should we throw an error? If yes, what should the CLI output?
- should this option work with `stdin`? If so, how does it work? If not, should we throw an error?

If you have questions, please use the issue and we will answer them

**Review by ematipico — CHANGES_REQUESTED** [review]
I'm going to block it because a lot of things are missing. We will use the relative issue to talk about it

**Comment by ematipico** [comment]
@Marcellofabrizio are you still interested?

**Comment by Marcellofabrizio** [comment]
@ematipico hey, sorry for the lack of reply. Let's close this. It would be a cool first contribution but it doesn't add much. Plus, as dyc3, this can be done with `>`.

**Pull request closed without merging**
