### PR TITLE
challenge: don't reformat snapshots

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

The `prepare-test` extract and reformat the expected output of a prettier test.
This presents several issues:

- This hides reformats issues of prettier
- This reports erroneous differences for range formatting.

The reformat is done to ensure that we compare an output with the same set of options.
However, the prettier tests seem to use already the default options.

This PR removes the reformatting of the expected outputs.

## Test Plan

Updated snapshots.

### CODE REVIEW

**Comment by ematipico** [comment]
Does that mean that all new diffs are generated because prettier is not idempotent?? 

This is wild...

**Comment by Conaclos** [comment]
> Does that mean that all new diffs are generated because prettier is not idempotent??

I didn't check every one, however most of them seems indeed non-idempotent formatting.

**Comment by ematipico** [comment]
Perfect, we discussed this offline.

 Prettier issues (idempotent) should not be inherited in Biome. We can update our snapshots to signal the issue, but we should still do a double format and use the second output.

**Review by xxchan — COMMENTED** [review]
After this, prettier compatibility increases to 94.57% 🤣

**Comment by Conaclos** [comment]
CLosing in favor of #790 and #774.

**Comment by Conaclos** [comment]
Closing in favor of https://github.com/biomejs/biome/pull/790 and https://github.com/biomejs/biome/pull/774.

**Pull request closed without merging**
