### PR TITLE
feat(biome_js_analyze): noTsIgnoreComment add initial rule

### PR DESCRIPTION
**Pull request by emab**
## Summary

Implements `noTsIgnoreComment` rule, which prevents the use of `@ts-ignore`.

- https://github.com/biomejs/biome/issues/713

## Test Plan

TBC

### CODE REVIEW

**Comment by emab** [comment]
Bit of a work in progress.

Not sure if I should include an action to remove the comment, or replace with `ts-expect-error`.

**Comment by emab** [comment]
I'm guessing the performance hit is due to using `AnyJsModuleItem`?

I wasn't sure how to directly find only comment stings. Should I be using the semantic model instead?

**Comment by ematipico** [comment]
> I'm guessing the performance hit is due to using `AnyJsModuleItem`?
> 
> I wasn't sure how to directly find only comment stings. Should I be using the semantic model instead?

It's a false positive, don't worry

**Comment by ematipico** [comment]
> I wasn't sure how to directly find only comment stings. Should I be using the semantic model instead?

No. You only need to query the CST, comments are trivia and they have no part in the semantic model.

However, you have to widen the query. Comments can be anywhere! Technically, you'd need to query any node

**Comment by emab** [comment]
> No. You only need to query the CST, comments are trivia and they have no part in the semantic model.
> 

Okay cool, I thought that was the case!

> However, you have to widen the query. Comments can be anywhere! Technically, you'd need to query any node
> 

Ah so right now I'll be missing comments within module items I suppose?

I was hoping I'd be able to match on a comment line, but since it's trivia I assume I'll need to search for any node and collect matching ts ignore trivia's?

**Comment by ematipico** [comment]
> I was hoping I'd be able to match on a comment line, but since it's trivia I assume I'll need to search for any node and collect matching ts ignore trivia's?

Yeah, that's right. There was this old initial implementation that you could use as a source of inspiration: https://github.com/rome/tools/pull/2811/files 
Be mindful that the PR was closed, which means that some cases weren't caught. Also, as a piece of personal advice, I would avoid a code action for now. Working with trivia and mutations can be tricky.

**Comment by emab** [comment]
> Yeah, that's right. There was this old initial implementation that you could use as a source of inspiration: https://github.com/rome/tools/pull/2811/files Be mindful that the PR was closed, which means that some cases weren't caught. Also, as a piece of personal advice, I would avoid a code action for now. Working with trivia and mutations can be tricky.

Thanks for sharing that. I guess my question now is - are the performance issues mentioned now no longer a problem?

Also:

> ability for lint rules (and visitors) to inspect syntax tokens (currently lint rules can only query AST nodes)

Am I correct in thinking we can now query syntax tokens? Should I be querying these in order to catch the edge cases? Quite new to this world so apologies if these are simple questions!

**Comment by adriencaccia** [comment]
> > I'm guessing the performance hit is due to using `AnyJsModuleItem`?
> 
> It's a false positive, don't worry

Hey @ematipico, we released a feature to ignore benchmarks that have a tendency to be flaky.
You can ignore the [benchmark `big5-added.json[uncached]` on its dashboard page](https://codspeed.io/biomejs/biome/benchmarks/xtask/bench/benches/json_parser.rs::json_parser::bench_json_parser::json_parser::big5-added.json[uncached]?branchId=66282a07ddf65bd2bf987327).
This is not ideal, but sometimes the code used in some benchmarks is by definition not deterministic, so removing them from the report is preferrable to avoid noise. Ignored benchmarks are still measured at every run though, and their history can still be accessed on CodSpeed 😉

**Comment by ematipico** [comment]
Hey @adriencaccia! That's an amazing feature, thank you for implementing that, I will start ignoring flaky benchmarks now :)

**Comment by ematipico** [comment]
> Am I correct in thinking we can now query syntax tokens? Should I be querying these in order to catch the edge cases? Quite new to this world so apologies if these are simple questions!

You can give it a try, let's see how it goes!

**Comment by ematipico** [comment]
@emab are you still interested in this PR?

**Comment by ematipico** [comment]
I am going to close it.

**Pull request closed without merging**
