### PR TITLE
build: set `codegen-units = 1`

### PR DESCRIPTION
**Pull request by Gumichocopengin8**
## Summary
`codegen-units = 1` flags usually optimizes performance, but the results are actually opaque. Do you think it's worth adding the flag? Downside of this flag is longer build time.

## Test Plan
- CI should pass

### CODE REVIEW

**Comment by Gumichocopengin8** [comment]
!bench_formatter
!bench_parser
!bench_analyzer

**Comment by Conaclos** [comment]
Based on the benchmark this seems make perf worst.
I think we should investigate why.

In the meantime, I think it is not a good idea to turn on.

**Comment by Gumichocopengin8** [comment]
What's the best way to investigate this type of issue in general?

**Comment by nissy-dev** [comment]
There is no active movement, so I closed the issue. I think it would be a good idea to create an issue and discuss performance before creating PR.

**Pull request closed without merging**
