### PR TITLE
chore: rename `rome_cli` to `biome_cli`

### PR DESCRIPTION
**Pull request by nhedger**
## Summary

This PR renames the `rome_cli` crate to `biome_cli`

## Test Plan

Ran a build and the tests

### CODE REVIEW

**Comment by nhedger** [comment]
Just saw that a few style changes were committed with this by mistake

**Comment by ematipico** [comment]
@nhedger to format the project, use the command `just f`

**Comment by nhedger** [comment]
Will do, thanks

**Review by ematipico — APPROVED** [review]

**Comment by nhedger** [comment]
Thank you, @ematipico!

**Pull request merged**
