### PR TITLE
refactor(lint/noUnusedLabels): make code fix safe

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

Make code fix of [noUnusedLabels](https://biomejs.dev/linter/rules/no-unused-labels).

I also improved the implementation by reducing the memory usage of the visitor.
The mutation also uses safer API.

By the way, I wonder if we should reduce the scope of the rule.
For now the rule applies to all labeled statements. However, there are some labeled statement that always unused by nature.
For example:

```js
function sqrt(n) {
    DEV: assert(n >= 0);
}
```

We could only report breakable statements (basically statement that can contain other statements)?
Non-breakable statements (and some breakable statements) are already covered by [noConfusingLabels](https://biomejs.dev/linter/rules/no-confusing-labels).
Any though?

## Test Plan

Tests updated.

### CODE REVIEW

**Comment by ematipico** [comment]
!bench_analyzer

**Comment by ematipico** [comment]
Can you explain the nature of the example? Is there some context we don't have? To me it only seems like a snippet where the rule is correctly triggered.

**Comment by Conaclos** [comment]
> Can you explain the nature of the example? Is there some context we don't have? To me it only seems like a snippet where the rule is correctly triggered.

The rule is in correctness category because `Labels that are declared and never used are most likely an error due to incomplete refactoring`.

However, some labels don't fit this description.
Indeed, users can deliberately use a label on an unbreakable statement.
This is sometimes (rarely) used to mark a statement to drop at build time.
ESbuild provides [an option to remove statements labelled with a given label](https://esbuild.github.io/api/#drop-labels).

Since this doesn't fit the rule description / category, and there are uses of these labels, I propose that `noUnusedLabels` reports only unused labels of breakable statements.
Unbreakable statements are still reported via `noConfusingLabel`. Thus, a user that uses labels for unbreakable statements could disable `noConfusingLabel` and still benefit of `noUnusedLabels`.

**Comment by ematipico** [comment]
Thank you for the explanation!

**Review by ematipico — APPROVED** [review]

**Pull request merged**
