### PR TITLE
chore: rename `rome_flags` to `biome_flags`, `rome_aria_metadata` to`biome_aria_metadata` and `rome_aria` to`biome_aria` biomejs#88

### PR DESCRIPTION
**Pull request by kyu08**
## Summary
- rename `rome_flags` to `biome_flags`
- rename `rome_aria_metadata` to `biome_aria_metadata`
- rename `rome_aria` to `tobiome_aria`

#88 

## Test Plan
- [x] `cargo test`

### CODE REVIEW

**Comment by ematipico** [comment]
Thank you! It seems that there are conflicts now

**Comment by kyu08** [comment]
@ematipico 
I'm done! Could you check it please?

**Comment by kyu08** [comment]
It seems like there are conflicts again. I'll fix it later.

**Comment by ematipico** [comment]
- Run the command `just format` to format all files, `.toml` files included;
- in `generate_configuration.rs`, there's code that needs to be updated:

https://github.com/biomejs/biome/blob/717232e6c09c45e7563a767eb03388adfafcfb58/xtask/codegen/src/generate_configuration.rs#L157

I suggest the following workflow:
1. `cargo codegen-configuration`
2. `just lint`

**Comment by kyu08** [comment]
I fixed conflicts but still got errors provided by executing `just ready` so I'll fix it later.

**Comment by ematipico** [comment]
> I fixed conflicts but still got errors provided by executing `just ready` so I'll fix it later.

It seems that there's only a `Cargo.lock` issue. You're almost there! 😄

**Comment by kyu08** [comment]
@ematipico 
Thanks!
When I ran `just ready`, I got these errors.

<details><summary>All errors and warnings I got</summary>
<p>

```sh
   --> crates/rome_js_semantic/src/events.rs:126:36
    |
126 | /// Extracts [SemanticEvent] from [SyntaxNode].
    |                                    ^^^^^^^^^^ no item named `SyntaxNode` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
    = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default

warning: public documentation for `SemanticEventExtractor` links to private item `SemanticEventIterator`
   --> crates/rome_js_semantic/src/events.rs:134:76
    |
134 | /// For a simpler way to extract [SemanticEvent] see [semantic_events] or [SemanticEventIterator].
    |                                                                            ^^^^^^^^^^^^^^^^^^^^^ this item is private
    |
    = note: this link will resolve properly if you pass `--document-private-items`
    = note: `#[warn(rustdoc::private_intra_doc_links)]` on by default

warning: unresolved link to `PreOrder`
   --> crates/rome_js_semantic/src/events.rs:137:10
    |
137 | /// the [PreOrder] of the tree, and must pull events until [Pop] returns [None].
    |          ^^^^^^^^ no item named `PreOrder` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `Pop`
   --> crates/rome_js_semantic/src/events.rs:137:61
    |
137 | /// the [PreOrder] of the tree, and must pull events until [Pop] returns [None].
    |                                                             ^^^ no item named `Pop` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `SyntaxNode`
    --> crates/rome_js_semantic/src/events.rs:1036:36
     |
1036 | /// Extracts [SemanticEvent] from [SyntaxNode].
     |                                    ^^^^^^^^^^ no item named `SyntaxNode` in scope
     |
     = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `SyntaxNode`
 --> crates/rome_js_semantic/src/semantic_model/builder.rs:6:63
  |
6 | /// Builds the [SemanticModel] consuming [SemanticEvent] and [SyntaxNode].
  |                                                               ^^^^^^^^^^ no item named `SyntaxNode` in scope
  |
  = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `SemanticEvents`
 --> crates/rome_js_semantic/src/semantic_model/builder.rs:9:46
  |
9 | /// [SemanticModelBuilder] consumes all the [SemanticEvents] and build all the
  |                                              ^^^^^^^^^^^^^^ no item named `SemanticEvents` in scope
  |
  = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: public documentation for `SemanticModelBuilder` links to private item `SemanticModelData`
  --> crates/rome_js_semantic/src/semantic_model/builder.rs:10:32
   |
10 | /// data necessary to build a [SemanticModelData], that is allocated with an [Arc]
   |                                ^^^^^^^^^^^^^^^^^ this item is private
   |
   = note: this link will resolve properly if you pass `--document-private-items`

warning: unresolved link to `Arc`
  --> crates/rome_js_semantic/src/semantic_model/builder.rs:10:79
   |
10 | /// data necessary to build a [SemanticModelData], that is allocated with an [Arc]
   |                                                                               ^^^ no item named `Arc` in scope
   |
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: public documentation for `SemanticModel` links to private item `scope`
   --> crates/rome_js_semantic/src/semantic_model/model.rs:105:15
    |
105 | /// - Scope: [scope]
    |               ^^^^^ this item is private
    |
    = note: this link will resolve properly if you pass `--document-private-items`

warning: unresolved link to `declaration`
   --> crates/rome_js_semantic/src/semantic_model/model.rs:106:22
    |
106 | /// - Declarations: [declaration]
    |                      ^^^^^^^^^^^ no item named `declaration` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: public documentation for `SemanticModel` links to private item `SemanticModelData`
   --> crates/rome_js_semantic/src/semantic_model/model.rs:108:10
    |
108 | /// See [SemanticModelData] for more information about the internals.
    |          ^^^^^^^^^^^^^^^^^ this item is private
    |
    = note: this link will resolve properly if you pass `--document-private-items`

warning: unresolved link to `Call`
   --> crates/rome_js_semantic/src/semantic_model/model.rs:341:22
    |
341 |     /// Returns all [Call] of a [AnyJsFunction].
    |                      ^^^^ no item named `Call` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `Call`
   --> crates/rome_js_semantic/src/semantic_model/reference.rs:105:38
    |
105 |     /// Returns this reference as a [Call] if possible
    |                                      ^^^^ no item named `Call` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `ancestors`
   --> crates/rome_js_semantic/src/semantic_model/scope.rs:100:15
    |
100 |     /// that [ancestors] return "self" as the first scope,
    |               ^^^^^^^^^ no item named `ancestors` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `semantic_model::SemanticModel::scope`
   --> crates/rome_js_semantic/src/semantic_model/scope.rs:208:21
    |
208 |     /// See [scope](semantic_model::SemanticModel::scope)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `semantic_model` is a function, not a module or type, and cannot have associated items

warning: unresolved link to `semantic_model::SemanticModel::scope_hoisted_to`
   --> crates/rome_js_semantic/src/semantic_model/scope.rs:212:21
    |
212 |     /// See [scope](semantic_model::SemanticModel::scope_hoisted_to)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `semantic_model` is a function, not a module or type, and cannot have associated items

warning: unclosed HTML tag `bool`
   --> crates/rome_js_semantic/src/semantic_model/model.rs:298:65
    |
298 |     /// When a reference is specified this method returns Option<bool>,
    |                                                                 ^^^^^^
    |
    = note: `#[warn(rustdoc::invalid_html_tags)]` on by default
help: try marking as source code
    |
298 |     /// When a reference is specified this method returns `Option<bool>`,
    |                                                           +            +

warning: unclosed HTML tag `bool`
   --> crates/rome_js_semantic/src/semantic_model/model.rs:312:65
    |
312 |     /// When a reference is specified this method returns Option<bool>,
    |                                                                 ^^^^^^
    |
help: try marking as source code
    |
312 |     /// When a reference is specified this method returns `Option<bool>`,
    |                                                           +            +

   --> crates/rome_service/src/configuration/linter/rules.rs:371:5
    |
371 |     #[doc = "The scope prop should be used only on <th> elements."]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(rustdoc::invalid_html_tags)]` on by default

warning: unclosed HTML tag `T`
    --> crates/rome_service/src/configuration/linter/rules.rs:2914:5
     |
2914 |     #[doc = "When expressing array types, this rule promotes the usage of T[] shorthand instead of Array<T>."]
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
help: try marking as source code
     |
2914 |     `#[doc = "When expressing array types, this rule promotes the usage of T[] shorthand instead of Array<T>."]`
     |     +                                                                                                          +
  --> crates/rome_json_formatter/src/generated.rs:23:57
   |
23 |             crate::json::auxiliary::root::FormatJsonRoot::default(),
   |                                                         ^^^^^^^^^^^ help: remove this call to `default`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs
   = note: `-D clippy::default-constructed-unit-structs` implied by `-D warnings`

error: use of `default` to create a unit struct
  --> crates/rome_json_formatter/src/generated.rs:35:57
   |
35 |             crate::json::auxiliary::root::FormatJsonRoot::default(),
   |                                                         ^^^^^^^^^^^ help: remove this call to `default`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
  --> crates/rome_json_formatter/src/generated.rs:61:68
   |
61 |             crate::json::value::string_value::FormatJsonStringValue::default(),
   |                                                                    ^^^^^^^^^^^ help: remove this call to `default`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
  --> crates/rome_json_formatter/src/generated.rs:73:68
   |
73 |             crate::json::value::string_value::FormatJsonStringValue::default(),
   |                                                                    ^^^^^^^^^^^ help: remove this call to `default`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
  --> crates/rome_json_formatter/src/generated.rs:99:70
   |
99 |             crate::json::value::boolean_value::FormatJsonBooleanValue::default(),
   |                                                                      ^^^^^^^^^^^ help: remove this call to `default`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:111:70
    |
111 |             crate::json::value::boolean_value::FormatJsonBooleanValue::default(),
    |                                                                      ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:137:64
    |
137 |             crate::json::value::null_value::FormatJsonNullValue::default(),
    |                                                                ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:149:64
    |
149 |             crate::json::value::null_value::FormatJsonNullValue::default(),
    |                                                                ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:175:68
    |
175 |             crate::json::value::number_value::FormatJsonNumberValue::default(),
    |                                                                    ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:187:68
    |
187 |             crate::json::value::number_value::FormatJsonNumberValue::default(),
    |                                                                    ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:213:66
    |
213 |             crate::json::value::array_value::FormatJsonArrayValue::default(),
    |                                                                  ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:225:66
    |
225 |             crate::json::value::array_value::FormatJsonArrayValue::default(),
    |                                                                  ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:251:68
    |
251 |             crate::json::value::object_value::FormatJsonObjectValue::default(),
    |                                                                    ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:263:68
    |
263 |             crate::json::value::object_value::FormatJsonObjectValue::default(),
    |                                                                    ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:283:61
    |
283 |             crate::json::auxiliary::member::FormatJsonMember::default(),
    |                                                             ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:295:61
    |
295 |             crate::json::auxiliary::member::FormatJsonMember::default(),
    |                                                             ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:321:70
    |
321 |             crate::json::auxiliary::member_name::FormatJsonMemberName::default(),
    |                                                                      ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:333:70
    |
333 |             crate::json::auxiliary::member_name::FormatJsonMemberName::default(),
    |                                                                      ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:346:79
    |
346 |             crate::json::lists::array_element_list::FormatJsonArrayElementList::default(),
    |                                                                               ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:358:79
    |
358 |             crate::json::lists::array_element_list::FormatJsonArrayElementList::default(),
    |                                                                               ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:371:66
    |
371 |             crate::json::lists::member_list::FormatJsonMemberList::default(),
    |                                                                  ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:383:66
    |
383 |             crate::json::lists::member_list::FormatJsonMemberList::default(),
    |                                                                  ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:401:80
    |
401 |         FormatRefWithRule::new(self, crate::json::bogus::bogus::FormatJsonBogus::default())
    |                                                                                ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:410:82
    |
410 |         FormatOwnedWithRule::new(self, crate::json::bogus::bogus::FormatJsonBogus::default())
    |                                                                                  ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:435:66
    |
435 |             crate::json::bogus::bogus_value::FormatJsonBogusValue::default(),
    |                                                                  ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:447:66
    |
447 |             crate::json::bogus::bogus_value::FormatJsonBogusValue::default(),
    |                                                                  ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:458:81
    |
458 |         FormatRefWithRule::new(self, crate::json::any::value::FormatAnyJsonValue::default())
    |                                                                                 ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: use of `default` to create a unit struct
   --> crates/rome_json_formatter/src/generated.rs:467:83
    |
467 |         FormatOwnedWithRule::new(self, crate::json::any::value::FormatAnyJsonValue::default())
    |                                                                                   ^^^^^^^^^^^ help: remove this call to `default`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

error: could not compile `rome_json_formatter` (lib) due to 28 previous errors

Caused by:
  process didn't exit successfully: `/Users/${user_name}/.rustup/toolchains/1.72.0-aarch64-apple-darwin/bin/clippy-driver /Users/${user_name}/.rustup/toolchains/1.72.0-aarch64-apple-darwin/bin/rustc --crate-name rome_json_formatter --edition=2021 crates/rome_json_formatter/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=200 --crate-type lib --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -C metadata=dd09da42e57b6561 -C extra-filename=-dd09da42e57b6561 --out-dir /Users/${user_name}/code/rust/biome/target/debug/deps -C incremental=/Users/${user_name}/code/rust/biome/target/debug/incremental -L dependency=/Users/${user_name}/code/rust/biome/target/debug/deps --extern rome_diagnostics=/Users/${user_name}/code/rust/biome/target/debug/deps/librome_diagnostics-a0a6d7d36596e856.rmeta --extern rome_formatter=/Users/${user_name}/code/rust/biome/target/debug/deps/librome_formatter-9e1f1d186349a0f6.rmeta --extern rome_json_syntax=/Users/${user_name}/code/rust/biome/target/debug/deps/librome_json_syntax-7bef5e14e53f2491.rmeta --extern rome_rowan=/Users/${user_name}/code/rust/biome/target/debug/deps/librome_rowan-c5d14f863285342f.rmeta --extern rome_suppression=/Users/${user_name}/code/rust/biome/target/debug/deps/librome_suppression-03397d5fefec1ea1.rmeta` (exit status: 1)
warning: build failed, waiting for other jobs to finish...
error: Recipe `lint` failed on line 102 with exit code 101
error: Recipe `ready` failed on line 110 with exit code 101

```

</p>
</details> 

At first, I'll try to fix errors and warnings I might be able to fix.
And I don't have any idea to fix some of them like below. Please help me! 🙇 


## 1
It seems like public documentation references a private item. (I have no idea to fix this. Please Help! 🙇‍♂️)
```sh
warning: public documentation for `SemanticEventExtractor` links to private item `SemanticEventIterator`
   --> crates/rome_js_semantic/src/events.rs:134:76
    |
134 | /// For a simpler way to extract [SemanticEvent] see [semantic_events] or [SemanticEventIterator].
    |                                                                            ^^^^^^^^^^^^^^^^^^^^^ this item is private
    |
    = note: this link will resolve properly if you pass `--document-private-items`
    = note: `#[warn(rustdoc::private_intra_doc_links)]` on by default
```

## 2
What I should do is just escape like `\[PreOrder\]`? Or this reference is invalid?
```sh
warning: unresolved link to `PreOrder`
   --> crates/rome_js_semantic/src/events.rs:137:10
    |
137 | /// the [PreOrder] of the tree, and must pull events until [Pop] returns [None].
    |          ^^^^^^^^ no item named `PreOrder` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
```

## 3
I don't have any idea to fix this. 🙇‍♂️
```sh
warning: unresolved link to `semantic_model::SemanticModel::scope`
   --> crates/rome_js_semantic/src/semantic_model/scope.rs:208:21
    |
208 |     /// See [scope](semantic_model::SemanticModel::scope)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `semantic_model` is a function, not a module or type, and cannot have associated items
```
## 4
It seems like I should update codes as source code like help shows.
```sh
warning: unclosed HTML tag `bool`
   --> crates/rome_js_semantic/src/semantic_model/model.rs:298:65
    |
298 |     /// When a reference is specified this method returns Option<bool>,
    |                                                                 ^^^^^^
    |
    = note: `#[warn(rustdoc::invalid_html_tags)]` on by default
help: try marking as source code
    |
298 |     /// When a reference is specified this method returns `Option<bool>`,
    |                                                           +            +
```

**Comment by kyu08** [comment]
I fixed all errors and warnings that I could fix and CI passed! (I realized that simply I did't have to push diff of the file `**/generated.rs`. But it seems weird that executing `just ready` generates codes that don't pass CI).

If it is not big problem, is it possible to leave some warnings I showed above?

**Review by nissy-dev — APPROVED** [review]
Thanks! LGTM 👍

**Comment by kyu08** [comment]
@ematipico @nissy-dev 
Thank you for reviewing and helping me! ☺️

**Pull request merged**
