### PR TITLE
fix: updated query feature range interval format

### PR DESCRIPTION
**Pull request by blaze-d83**
## Summary

Resolving issue #4076 highlighted by @nstepien 

- I was able to pinpoint where the format originated from.
- Added the missing space() which should implement the desired format

### CODE REVIEW

**Review by ematipico — CHANGES_REQUESTED** [review]
Can you please add a test?

**Comment by blaze-d83** [comment]
@ematipico 

Hey hi!

Can you help me with this?

image

I tried to run test for the biome_css_formatter crate, but there this issue which wont let me do it.

Thanks!

**Comment by dyc3** [comment]
@blaze-d83 Try `cargo clean` first to clear the build cache.

**Comment by blaze-d83** [comment]
> @blaze-d83 Try `cargo clean` first to clear the build cache.

Yup. Tried that too. Still doesnt work.

I wonder if any thing is wrong with my approach:

1. I created query_interval_test.css file with the following:

```
.class {
	@media (1024px <= width <= 1280px) {
		color: red;
	}
}
```

2. Planning to run test for the crate biome_css_formatter

3. Review and accept the snap.

Thanks in advance

**Pull request merged**
