### PR TITLE
challenge(formatter): add a block indent to dangling comments

### PR DESCRIPTION
**Pull request by TaKO8Ki**
## Summary

Fix [typescript/tuple/dangling-comments.ts](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report_incompatible.md#typescripttupledangling-commentsts)

## Test Plan

All existing tests including prettier tests should pass.

### CODE REVIEW

**Review by ematipico — APPROVED** [review]
Easy and effective contribution!

**Comment by TaKO8Ki** [comment]
Should I rerun CI? It seems that some tests were cancelled.

**Comment by ematipico** [comment]
> Should I rerun CI? It seems that some tests were cancelled.

That's on me, sorry. I stopped a workflow by mistake

**Review by Conaclos — APPROVED** [review]

**Comment by TaKO8Ki** [comment]
@ematipico I see. No problem :)

**Pull request merged**
