### PR TITLE
fix(documentation): add link to external article

### PR DESCRIPTION
**Pull request by yndajas**
## Summary

Presumably a link was meant to be included to this article here

Also fixed a couple of headings in the changelog

### CODE REVIEW

**Review by Conaclos — APPROVED** [review]
Thanks!

**Comment by Conaclos** [comment]
You have to run `just gen-web`

**Comment by yndajas** [comment]
> You have to run `just gen-web`

I don't have Rust set up locally at the moment, but I can try to do this tomorrow

**Comment by yndajas** [comment]
> You have to run `just gen-web`

Okay, installed (didn't take that long!), but I'm not getting any errors locally - are you expecting there to be any? It looks like it just needed a rebase to me, which I've done

**Comment by ematipico** [comment]
> > You have to run `just gen-web`
> 
> Okay, installed (didn't take that long!), but I'm not getting any errors locally - are you expecting there to be any? It looks like it just needed a rebase to me, which I've done

The command will generate some files that will have to be committed

**Comment by ematipico** [comment]
Yeah that's correct. Let's see what the CI says. If it fails, I will give a hand

**Pull request merged**
