### PR TITLE
fix(tooling): update the script to bump the nightly version

### LINKED ISSUE #860: 📎 fix nightly version number
### Description

When we publish a nightly, we always take the current version and add a tag. As a result, this nightly is never higher than the current version.

We should fix this issue, by bumping the current version and then add the nightly tag

### PR DESCRIPTION
**Pull request by chansuke**
## Summary

Fixes #860.

Bump `version` of nightly in the script.

### CODE REVIEW

**Comment by Conaclos** [comment]
Thanks for taking care of this fix :)

I think we should bump the minor version instead of the patch. What do you think @ematipico?

**Comment by ematipico** [comment]
I don't have options, any version is fine as long as it is higher than the previous

**Comment by Conaclos** [comment]
> Thanks for taking care of this fix :)
> 
> I think we should bump the minor version instead of the patch. What do you think @ematipico?

@chansuke
Any opinion?

**Comment by chansuke** [comment]
@Conaclos I think that patch is better option

**Comment by nhedger** [comment]
Nightly version could also just be date time based

**Review by Conaclos — APPROVED** [review]

**Pull request merged**
