### PR TITLE
chore(linter): rename `useExplicitFunctionReturnType` to `useExplicit…

### PR DESCRIPTION
**Pull request by kaykdm**
…Type`

## Summary
related: https://github.com/biomejs/biome/issues/2017
rename `useExplicitFunctionReturnType` to `useExplicitType` 
Before implementing the `typescript-eslint/explicit-module-boundary-types` rule, I renamed it for better accuracy, as discussed in the issue [here ](https://github.com/biomejs/biome/discussions/3#discussioncomment-7575169).

### CODE REVIEW

**Review by ematipico — APPROVED** [review]

**Comment by Conaclos** [comment]
@kaykdm The rule you implemented is not meant to cover both all cases of #2017? Why did you rename the rule then?

**Comment by kaykdm** [comment]
@Conaclos 
Sorry for the late response.
-  I noticed the issue title after implementing the `typescript-eslint/explicit-function-return-type` rule and assumed that the rule name was already decided.
- I'm planning to implement the `typescript-eslint/explicit-module-boundary-types`  rule, so I thought it would make sense to rename the rule before proceeding with its implementation.

I don't mind reverting the rename PR if you'd prefer me to include the rename chore in the first PR with the new rule.

**Comment by Conaclos** [comment]
@kaykdm I am unsure to understand what you mean. Do you want to extend the current rule to cover #2017?

**Comment by kaykdm** [comment]
> Do you want to extend the current rule to cover https://github.com/biomejs/biome/issues/2017?

@Conaclos 
Yes, that was my plan, and I thought that was your plan too. If you think that we should separate the rule, that would be fine for me as well.

**Comment by Conaclos** [comment]
Thanks for the response, I will assign the task to you.

**Pull request merged**
