### PR TITLE
fix(css_formatter): fix CSS nesting whitespace after & trimmed #3061

### PR DESCRIPTION
**Pull request by denbezrukov**
## Summary

Close https://github.com/biomejs/biome/issues/3061

The problem arose from using the wrong lexer context after processing the '&' token.

## Test Plan

cargo test

### CODE REVIEW

**Review by ah-yu — APPROVED** [review]

**Comment by ah-yu** [comment]
Should we add extra space after the nesting selector if it has trailing comments? It seems Prettier doesn't handle the case very well 😅 [playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6SsCGBLKcBOABMADpQkwBkhNA9AFRj202ts3oAW2ANgCbEyFCpB4R8SQgCMeAVzgBuITAC+ZFSAA0ICAAcY2aAGdkoTPnwQA7gAVzCEykw8rmAJ4ntU-JjABrOBgAZUwAWzgAGVw4ZAAzZyM4Lx9-QKDdX1wAc2QYfHltRNDsXPykkDgAD10CbHCsHgAVAihzbDhHeJ5EwuyeOABFWQh4OITygCsjSqC+weHRpC6ekABHBbgbS11HEEwjAFo8OD4TrRA8nB5sgGEIUNDMZD2eHnOjOYBBGDzsKVl4DYCFE8GNuuVODBQjwAOrceBGDJgOBBBzYAwAN3RbmeYCMnhAGPkAEkoKdYEEwPhsPpPmSgjA3P0wStdJZEjCfLpnmyOgQMTFtLhEvgYFtMFlHizyhl8CLcfjzmzcDAYdg+DBOMgABwABm0+Dg62whvFkqeS3G2hgmCkao1WqQACZtLJEo1bZ0rRVQlITqc+BFMFAsrIJXAAGLiR4-bLPTAAiAgFQqIA)

**Comment by denbezrukov** [comment]
> Should we add extra space after the nesting selector if it has trailing comments? It seems Prettier doesn't handle the case very well 😅 [playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6SsCGBLKcBOABMADpQkwBkhNA9AFRj202ts3oAW2ANgCbEyFCpB4R8SQgCMeAVzgBuITAC+ZFSAA0ICAAcY2aAGdkoTPnwQA7gAVzCEykw8rmAJ4ntU-JjABrOBgAZUwAWzgAGVw4ZAAzZyM4Lx9-QKDdX1wAc2QYfHltRNDsXPykkDgAD10CbHCsHgAVAihzbDhHeJ5EwuyeOABFWQh4OITygCsjSqC+weHRpC6ekABHBbgbS11HEEwjAFo8OD4TrRA8nB5sgGEIUNDMZD2eHnOjOYBBGDzsKVl4DYCFE8GNuuVODBQjwAOrceBGDJgOBBBzYAwAN3RbmeYCMnhAGPkAEkoKdYEEwPhsPpPmSgjA3P0wStdJZEjCfLpnmyOgQMTFtLhEvgYFtMFlHizyhl8CLcfjzmzcDAYdg+DBOMgABwABm0+Dg62whvFkqeS3G2hgmCkao1WqQACZtLJEo1bZ0rRVQlITqc+BFMFAsrIJXAAGLiR4-bLPTAAiAgFQqIA)

Interesting, thank you for that case! Actually, I don't know; it seems that the parser returns an unknown selector if there is a comment between `&` and `.child`.

**Comment by denbezrukov** [comment]
Ive converted it to draft because after @ah-yu comment I think that it's a parser issue🙈

**Review by ematipico — APPROVED** [review]
Great fix @denbezrukov! Thank you ❤️

**Pull request merged**
