### PR TITLE
feat(lint): rule `noMisplacedAssertion`

### LINKED ISSUE #1848: ☂️ Lint rules for testing frameworks
### Description

We want to implement some lint rules to help people with their tests. I baked this list from the `eslint-plugin-jest` and evaluated only those rules that **aren't** pedantic and can be enabled for multiple test runners: `mocha`, `jest`, `node:test`, etc.

Feel free to comment here on which rule you would like to implement. We have some utilities that should help you to develop the rule: 
- https://github.com/biomejs/biome/blob/c5a98a72def0a1db072fc3face35cb30241608dd/crates/biome_js_syntax/src/expr_ext.rs#L1569
- https://github.com/biomejs/biome/blob/c5a98a72def0a1db072fc3face35cb30241608dd/crates/biome_js_syntax/src/expr_ext.rs#L1665
- https://github.com/biomejs/biome/blob/c5a98a72def0a1db072fc3face35cb30241608dd/crates/biome_js_syntax/src/expr_ext.rs#L1686

There are more functions in that files, feel free to explore.

This is an example of usage:

https://github.com/biomejs/biome/blob/c5a98a72def0a1db072fc3face35cb30241608dd/crates/biome_js_analyze/src/analyzers/nursery/no_focused_tests.rs#L43-L52

The names aren't set in stone, and feel free to suggest alternatives.

- [x] `noExportsInTest` [source](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-export.md) @ah-yu 
- [x] `noNestedTestSuites` [source](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/max-nested-describe.md) @vasucp1207 
- [x] `noDoneCallback` [source](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-done-callback.md) @vasucp1207
- [x] `noDuplicateTestHooks` [source](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-duplicate-hooks.md) @vasucp1207 
- [ ] `noMisplacedAssertion` [source](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-standalone-expect.md) @ematipico

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

This PR closes #1848 (last rule)

It implements the rule `noMisplacedAssertion`, which checks if `expect` or `assert` are called inside the `it` function.

This rule has options: users can define the name of the assertion functions and the specifiers from which these functions are imported.

## Test Plan

Added test cases

### CODE REVIEW

**Review by arendjr — APPROVED** [review]
Very nice!

**Comment by ipanasenko** [comment]
What about `waitFor` from testing-library? Their official docs recommend to use `expect` inside `waitFor` to wait for something: https://testing-library.com/docs/dom-testing-library/api-async#waitfor

**Comment by ipanasenko** [comment]
And maybe allow to use `expect()` inside other functions that start with `expect`? E.g. a common `const expectSomeStuffToMatch = (stuff) => expect(stuff).toMatch()`

**Comment by ematipico** [comment]
Hey @ipanasenko, thank you for your suggestions. I advise you to create a discussion, a thread on discord or a new issue. Commenting on closed PRs doesn't help the visibility of your suggestions.

**Pull request merged**
