### PR TITLE
fix(cli): ignore files and directories from working directory

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

Closes https://github.com/biomejs/biome/issues/1465
Closes https://github.com/biomejs/biome/issues/1471
Closes https://github.com/biomejs/biome/issues/1495
Closes https://github.com/biomejs/biome/issues/1504

~I nuked `globset`; it doesn't have what we need. Luckily, `ignore::gitignore` **does** what we need. It correctly resolves the globs based on a specified path, which is our working directory.~

> [!NOTE]
> We decided to revert the changes made in the recent release. The recent release removed our internal fork of 
> `glob` in favour of `globset`; unfortunately, after two days of tries and conversations with @Conaclos , we decided to **revert** the changes and use our own fork.

> [!IMPORTANT]
> Also, we decided to **NOT** pursue the parity with `git` glob patterns, because their semantics are very different. Did you know that in git, a pattern like `dist` is equivalent to `**/dist`? This means that a file with a path like `dist/test.js` WON'T match the previous `dist` glob.

I am sure that some users are very skilled in git, but most users usually use unix-style globs, which are simpler and more widespread.

I took the chance to update the documentation page with a better explanation of how the globs work inside Biome.

## Test Plan

1. I tested it on an actual project that specifies `src/**/*.js` as including globs.
2. I updated one of the tests with an incorrect assertion. Even globs that start with `/` e.g. `/src/**/*.js` are resolved from the working directory.

### CODE REVIEW

**Comment by Conaclos** [comment]
I tried to test this on a local project: it seems that `.gitignore` is no longer taken into account.

**Comment by Conaclos** [comment]
I compared Biome v1.4.1 with the current branch using a [dedicated reproduction](https://github.com/Conaclos/biome-1465): branches `main`, `variant1`, \variant2`, and `variant3`.

Biome v1.4.1 has the correct behavior ignoring both the `.gitignore` and `formatter.ignore`.
The current branches doesn't fix the issue for me and no longer take the `.gitignore` into account.

**Comment by ematipico** [comment]
This PR fixes cases where specifying a file in globs works. I checked the reproduction repository, and the `main` branch doesn't cover what's addressed here.

**Comment by ematipico** [comment]
@Conaclos the latest commit should address your repository case

**Comment by Conaclos** [comment]
> @Conaclos the latest commit should address your repository case

`.gitignore` is now taken int oaccount :)

However, it is still not working for `formatter.ignore`. Should I open another issue?

**Comment by ematipico** [comment]
What's the expected behaviour? You could create an issue that explains what we should expect.

I'll use this PR to fix it

**Comment by Conaclos** [comment]
> What's the expected behaviour?

The `tests` folder is listed in `formatter.ignore` in `biome.json`. Each branch uses a different syntax:

- main: `tests`
- variant1: `./tests`
- variant2: `.tests/*`
- variant3: `.tests/**/*`

I expect that running `biom format .` results in ignoring the `tests` folder.

**Review by Conaclos — APPROVED** [review]

**Pull request merged**
