### PR TITLE
doc(ja): translate `CLI` into Japanese

### PR DESCRIPTION
**Pull request by sakimyto**
## Summary

Partial work of https://github.com/biomejs/biome/issues/880 .
I've translated reference/cli.mdx.

I've noticed there are some default values missing in the docs. I think having a more consistent format for the documentation would really help make things clearer.

### CODE REVIEW

**Comment by ematipico** [comment]
FYI This page is automatically generated from the source code, maybe it should not be translated

**Comment by nissy-dev** [comment]
@ematipico Oh, I guess I couldn't check it properly... Thank you for pointing that out.

@sakimyto This file is automatically generated, so there is no need to translate it. I'm really sorry for the contribution you made 🙇

**Comment by sakimyto** [comment]
@nissy-dev Oh,OK.
I need to translate the other reference/vscode.mdx that I'm assigned to, right?

**Comment by nissy-dev** [comment]
@sakimyto 
> I need to translate the other reference/vscode.mdx that I'm assigned to, right?
Yes. `reference/vscode.mdx` is not auto-generated, so t would be helpful if you could translate it.

**Comment by unvalley** [comment]
@sakimyto We can always refer to this, so your work will not be in vain.

**Pull request closed without merging**
