### PR TITLE
doc(ja): translate `404 page` into Japanese

### PR DESCRIPTION
**Pull request by Gumichocopengin8**
## Summary

Partial work of #880. 404 page

## Test Plan
I made an issue https://github.com/withastro/starlight/issues/1154 about 404 page in starlight issue since 404 page is a special case. Looks like what we need to do to show 404 page is that make `ja/404.md` and setup `vercel.json`. Not 100% sure if this would work so if we have the website preview, we should def check it out.

### CODE REVIEW

**Comment by nissy-dev** [comment]
Thank you for your contribution and investigating the problem!

If there is some problems, I think there is no need to translate `404.md`. 
I'm very sorry, but I'll close this PR and update task list in #880.

**Comment by nissy-dev** [comment]
> ok sure, but 404 page already has the issue https://biomejs.dev/fdsa (this page isn't a valid page so we expect to see 404 page, but not really). 

Oh, I see. First, I try to check your vercel.json. If the PR is from a forked repository, preview-deploy job will not fire...

**Comment by Gumichocopengin8** [comment]
> > ok sure, but 404 page already has the issue https://biomejs.dev/fdsa (this page isn't a valid page so we expect to see 404 page, but not really).
> 
> Oh, I see. First, I try to check your vercel.json. If the PR is from a forked repository, preview-deploy job will not fire...

Got it. we can close this PR and you can make a PR with the code, then we see the website preview. What do you think?

**Comment by nissy-dev** [comment]
>  we can close this PR and you or other core member can make a PR with the code, then we see the website preview. What do you think?

I did in https://github.com/biomejs/biome/pull/956
And I don't know why, but the preview-deploy job ran in this PR, so I think we can confirm.

**Comment by nissy-dev** [comment]
It looks like the deployment is failing, can you confirm?

**Comment by Gumichocopengin8** [comment]
yeah looks like vercel.json pattern is not correct. could you try with https://github.com/withastro/starlight/blob/8d88850c64928878dc7d63c3ec90756690da8387/docs/vercel.json#L20 which is suggested in [this comment](https://github.com/withastro/starlight/issues/1154#issuecomment-1828748170)? I replace `routes` with `rewrite` cuz `routes` is not recommended anymore but for the testing purpose, we can use that one.

**Comment by Gumichocopengin8** [comment]
also, I'm not sure what is the right form to write `vercel.json` specifically for Starlight. I asked a question about [this](https://github.com/withastro/starlight/issues/1154#issuecomment-1831486741). until we get a response, we might need to try several times. If you or other contributors think its not worth it, I dont mind skipping this task.

**Comment by nissy-dev** [comment]
> also, I'm not sure what is the right form to write vercel.json specifically for Starlight. I asked a question about this. until we get a response, we might need to try several times. If you or other contributors think it's not worth it, I dont mind skipping this task.

I think your work is valuable, but I would appreciate it if you could confirm preview-deploy job works well in a forked repository before submitting a PR. I don't want to spend much time debugging in this PR, so I'll close it

**Pull request closed without merging**
