### PR TITLE
feat(format/grit): add logic for formatting with separators and other predicates

### PR DESCRIPTION
**Pull request by branberry**
## Summary

Add the ability to handle multi-line patterns that are separated with commas.

Added simple formatting rules for:
- accumulator predicate
- match predicate
- rewrite predicate

## Test Plan

Snapshot tests demonstrate correct formatting

### CODE REVIEW

**Review by dyc3 — APPROVED** [review]

**Comment by ematipico** [comment]
> Snapshot tests demonstrate correct formatting

Sorry @branberry, but I don't see any changes in the snapshots. The input and the output are the same. Usually, it's very useful to have your input unformatted (add some spaces or newlines around the implemented nodes), and if the output is different, and it's formatted the way you want. I suggest **to add** an unformatted case to your snapshot and also keep the formatted one.

https://github.com/branberry/biome/blob/8e243aee5da523897897a69c11f27f59a2381375/crates/biome_grit_formatter/tests/specs/grit/patterns/create_new_files.grit.snap#L5-L38

**Comment by branberry** [comment]
Oh, shoot! No need to apologize @ematipico. My apologies, I missed it. I thought I saw the correct formatting changes locally. Let me adjust this so that we have the desired formatting in the snapshot results. 

Thank you!

**Review by ematipico — APPROVED** [review]

**Comment by ematipico** [comment]
Don't worry, it's completely fine. This was more advice from a person who worked from the very beginning on the formatter. While things change, sometimes it's difficult to understand the wanted/expeted formatting. 

Having a "completely wrong" version of the input is a good way to visually see what changes

**Review by arendjr — APPROVED** [review]
:rocket:

**Pull request merged**
