### PR TITLE
fix(css_parser): fix the CSS parser doesn't support nested selectors with pseudo-classes #3287

### PR DESCRIPTION
**Pull request by denbezrukov**
## Summary

Fix https://github.com/biomejs/biome/issues/3287
Details see https://github.com/biomejs/biome/issues/3287

## Test Plan

`cargo test`

### CODE REVIEW

**Comment by denbezrukov** [comment]
## [CodSpeed Performance Report](https://codspeed.io/biomejs/biome/branches/fix/css-pseudo-classes)

### Merging #3318 will **degrade performances by 64.76%**

<sub>Comparing <code>fix/css-pseudo-classes</code> (b1235c6) with <code>main</code> (f741a13)</sub>



### Summary

`❌ 16` regressions
`✅ 74` untouched benchmarks



> :warning: _Please fix the performance issues or [acknowledge them on CodSpeed](https://codspeed.io/biomejs/biome/branches/fix/css-pseudo-classes)._

### Benchmarks breakdown

|     | Benchmark | `main` | `fix/css-pseudo-classes` | Change |
| --- | --------- | ----------------------- | ------------------- | ------ |
| ❌ | `bootstrap.css[cached]` | 46.9 ms | 127.7 ms | -63.26% |
| ❌ | `bootstrap.css[uncached]` | 50.8 ms | 134.5 ms | -62.28% |
| ❌ | `bulma.css[cached]` | 44.5 ms | 103.3 ms | -56.95% |
| ❌ | `bulma.css[uncached]` | 48.1 ms | 108.9 ms | -55.8% |
| ❌ | `foundation.css[cached]` | 30.1 ms | 76 ms | -60.35% |
| ❌ | `foundation.css[uncached]` | 32.1 ms | 79.3 ms | -59.49% |
| ❌ | `full.css[cached]` | 496.7 ms | 814.1 ms | -38.99% |
| ❌ | `full.css[uncached]` | 520.3 ms | 835.9 ms | -37.75% |
| ❌ | `materialize.css[cached]` | 32.9 ms | 83.4 ms | -60.48% |
| ❌ | `materialize.css[uncached]` | 36 ms | 88.3 ms | -59.19% |
| ❌ | `pure.css[cached]` | 3.9 ms | 8.5 ms | -54.72% |
| ❌ | `pure.css[uncached]` | 4.6 ms | 9.3 ms | -50.99% |
| ❌ | `semantic.css[cached]` | 141.1 ms | 310.7 ms | -54.58% |
| ❌ | `semantic.css[uncached]` | 152.2 ms | 320.9 ms | -52.57% |
| ❌ | `tachyons.css[cached]` | 21.5 ms | 60.9 ms | -64.76% |
| ❌ | `tachyons.css[uncached]` | 25 ms | 69.5 ms | -64.03% |

**Comment by ematipico** [comment]
It seems you last commit fixes the perf regression: https://codspeed.io/biomejs/biome/branches/fix/css-pseudo-classes

**Comment by denbezrukov** [comment]
@ematipico Hm, I need to check the snapshots, though. I might break something😥

I'd like to try one more approach by checking the identifier after `:` to understand if it is a selector. I don't know what the best solution here=(

**Comment by ematipico** [comment]
What are you trying to solve? Are you trying to distinguish? It isn't clear from the issue nor the PR description

**Comment by denbezrukov** [comment]
> What are you trying to solve? What are you trying to distinguish? It isn't clear from the issue or the PR description

Sorry for the misleading description.

I'm trying to distinguish this example:

```
.class {
     div:hover {.  <--- here it's a selector
        color: green;
     }
     
     background: red;  <--- here it's a declaration
}
```

A nested selector with a pseudo-class has the same structure as a declaration: [indent][colon]

https://github.com/biomejs/biome/issues/3287#issuecomment-2196097571

**Comment by ematipico** [comment]
Can't we break down the parsing of the selector to a minimum? 

For example, we know that if we find a `{`, it means we are paring a selector. If we encounter a `;` - in this example - we are parsing a declaration.

So we could the parsing **until `{`** inside its own function. I believe we use this strategy inside our JS parser here:

https://github.com/biomejs/biome/blob/a512d8104550ad0d2f0d29de9028a8e0b3d70689/crates/biome_js_parser/src/syntax/function.rs#L618-L620

**Comment by ematipico** [comment]
Yeah, I understand now. I wonder if we should check how other parsers solved this issue

**Comment by ematipico** [comment]
I thought about it more, and I think we should attempt the parsing of declarations first, then fallback to selectors. 

Nested selectors are a newer syntax, less spread across the current CSS files. Plus, ignoring how old their grammar is, I believe it's more probable to find decorations inside a selector, not other nested selectors.

**Comment by denbezrukov** [comment]
> I thought about it more, and I think we should attempt the parsing of declarations first, then fallback to selectors. 
> 
> Nested selectors are a newer syntax, less spread across the current CSS files. Plus, ignoring how old their grammar is, I believe it's more probable to find declarations inside a selector, not other nested selectors.

Yeah, I agree, let's try to keep this approach.
Anyway, I'd like to try comparing the next token after a colon. Actually it can be just a range compare and doesn't introduce huge impact in theory🙈

**Comment by denbezrukov** [comment]
I've checked the Lightlight CSS library, and they have a logic where they first parse as a declaration and, if it fails, they parse as a rule. I'd suggest choosing this approach.

https://github.com/servo/rust-cssparser/blob/b75ce6a8df2dbd712fac9d49ba38ee09b96d0d52/src/rules_and_declarations.rs#L263-L300

**Comment by ematipico** [comment]
Looks good to me!

**Pull request merged**
