### PR TITLE
fix(js_lexer): regex escape char

### LINKED ISSUE #1941: 🐛 Including smart-quote `‘` with escape `\` confuses the JS lexer
### Environment information

```block
CLI:
  Version:                      1.5.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.7.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

1. In the playground, paste in
```js
"hello world".replace(/\’/, "")
```

or put that in a .js file and run `biome lint` against it.

---
The `biome lint` gives this output:

```
src/js/test.js:1:28 parse ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ unterminated regex literal

  > 1 │ "hello".replace(/\‘/, "'");
      │
    2 │

  ℹ ...but the line ends here

  > 1 │ "hello".replace(/\‘/, "'");
      │
    2 │

  ℹ a regex literal starts there...

  > 1 │ "hello".replace(/\‘/, "'");
      │                 ^
    2 │


src/js/test.js:2:1 parse ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ expected `)` but instead the file ends

    1 │ "hello".replace(/\‘/, "'");
  > 2 │
      │

  ℹ the file ends here

    1 │ "hello".replace(/\‘/, "'");
  > 2 │
      │


src/js/test.js lint ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ The file contains diagnostics that needs to be addressed.


Checked 1 file(s) in 15ms
Found 3 error(s)
lint ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Some errors were emitted while running checks.
```

---
The playground crashes completely, and shows this in the browser console:

```
client.LpXbfsP5.js:24 RangeError: Invalid position 33 in document of length 31
    at qe.lineAt (PlaygroundLoader.O4NTypk8.js:1:4066)
    at SA (PlaygroundLoader.O4NTypk8.js:10:41341)
    at li.update [as updateF] (PlaygroundLoader.O4NTypk8.js:10:41717)
    at Object.update (PlaygroundLoader.O4NTypk8.js:4:17201)
    at ke.computeSlot (PlaygroundLoader.O4NTypk8.js:4:25884)
    at _c (PlaygroundLoader.O4NTypk8.js:4:20008)
    at new ke (PlaygroundLoader.O4NTypk8.js:4:25071)
    at ke.applyTransaction (PlaygroundLoader.O4NTypk8.js:4:25853)
    at get state (PlaygroundLoader.O4NTypk8.js:4:21482)
    at Rt.update (PlaygroundLoader.O4NTypk8.js:9:14200)
pi @ client.LpXbfsP5.js:24
t.callback @ client.LpXbfsP5.js:24
eo @ client.LpXbfsP5.js:22
go @ client.LpXbfsP5.js:24
ha @ client.LpXbfsP5.js:24
kf @ client.LpXbfsP5.js:24
_f @ client.LpXbfsP5.js:24
yn @ client.LpXbfsP5.js:24
So @ client.LpXbfsP5.js:24
pn @ client.LpXbfsP5.js:22
Xn @ client.LpXbfsP5.js:24
(anonymous) @ client.LpXbfsP5.js:24
E @ client.LpXbfsP5.js:9
lt @ client.LpXbfsP5.js:9
client.LpXbfsP5.js:22 Uncaught RangeError: Invalid position 33 in document of length 31
    at qe.lineAt (PlaygroundLoader.O4NTypk8.js:1:4066)
    at SA (PlaygroundLoader.O4NTypk8.js:10:41341)
    at li.update [as updateF] (PlaygroundLoader.O4NTypk8.js:10:41717)
    at Object.update (PlaygroundLoader.O4NTypk8.js:4:17201)
    at ke.computeSlot (PlaygroundLoader.O4NTypk8.js:4:25884)
    at _c (PlaygroundLoader.O4NTypk8.js:4:20008)
    at new ke (PlaygroundLoader.O4NTypk8.js:4:25071)
    at ke.applyTransaction (PlaygroundLoader.O4NTypk8.js:4:25853)
    at get state (PlaygroundLoader.O4NTypk8.js:4:21482)
    at Rt.update (PlaygroundLoader.O4NTypk8.js:9:14200)
```

---

Trying to run `biome format` on it gives:
```
./node_modules/@biomejs/biome/bin/biome format --verbose  src/js/test.js
src/js/test.js format ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Format with errors is disabled.

```

---

This also happens with other similar types of "smart" quotes, 
```js
"hello world".replace(/\‟/, "")
```
for instance.

### Expected result

It should work just fine, the same as
```
"hello world".replace(/\'/, "")
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by Sec-ant**
## Summary

After the lexer reads an escape char `\` in a regular expression, it should advance a byte or a char, so that valid regexes like `/\’/` won't fail.

Fixes #1941.

## Test Plan

A test case is added in `crates/biome_js_parser/test_data/inline/ok/literals.js`

### CODE REVIEW

**Comment by arendjr** [comment]
Nice! I would appreciate if we can add a test case for this, but the fix makes sense :+1:

**Comment by arendjr** [comment]
Lexer test cases can be added here, btw: https://github.com/biomejs/biome/blob/main/crates/biome_js_parser/src/lexer/tests.rs

**Comment by Conaclos** [comment]
Could you add a changelog entry in `CHANGELOG.md`? I just committed the `Unreleased section` on main. You could rebase your PR on maim :)

**Comment by Sec-ant** [comment]
> Lexer test cases can be added here, btw: https://github.com/biomejs/biome/blob/main/crates/biome_js_parser/src/lexer/tests.rs

Yes I was hoping to add a test here, something like this:

```rust
#[test]
fn issue_1941() {
    assert_lex! {
        r#"/\’/"#,
        JS_REGEX_LITERAL:6
    }
}
```

But the lexer needs some context to read this as a regex, or it will produce `SLASH:1` `ERROR:1` `ERROR:3` `SLASH:1`. I don't know how should I give it the proper context?

**Comment by arendjr** [comment]
I think `r#"let a = /\’/"#` should do the trick.

**Comment by Sec-ant** [comment]
> I think `r#"let a = /\’/"#` should do the trick.

Still slash and error token. Did I do something wrong?

```shell
[
    (
        LET_KW,
        0..3,
    ),
    (
        WHITESPACE,
        3..4,
    ),
    (
        IDENT,
        4..5,
    ),
    (
        WHITESPACE,
        5..6,
    ),
    (
        EQ,
        6..7,
    ),
    (
        WHITESPACE,
        7..8,
    ),
    (
        SLASH,
        8..9,
    ),
    (
        ERROR_TOKEN,
        9..10,
    ),
    (
        ERROR_TOKEN,
        10..13,
    ),
    (
        SLASH,
        13..14,
    ),
]
```

**Comment by arendjr** [comment]
No, it's not your fault. It looks like the lexer cannot determine the presence of regexes on its own. It only happens after the parser tells it to "re-lex" certain nodes. So instead, I think you should add your test case here: https://github.com/biomejs/biome/blob/main/crates/biome_js_parser/test_data/inline/ok/literals.js

**Review by arendjr — APPROVED** [review]
Looks good!

**Comment by arendjr** [comment]
> Should I add changelogs for other PRs (post v1.60) as well? Some are already merged.

Might be better to do that in a separate PR, I think.

**Comment by arendjr** [comment]
Could you run the codegen one more time to update the changelog for the website?

**Comment by arendjr** [comment]
Thanks for the patch!

**Pull request merged**
