### PR TITLE
challenge(formatter): handle line break and comments for array holes

### PR DESCRIPTION
**Pull request by victor-teles**
## Summary
This PR fixes comments placement for array holes.

partially fixes js/arrays/numbers-with-holes.js

~I've to introduced a new `entry_with_separator` method for less generic line breaking in arrays as holes need it's own logic.~

I going to work in line breaking limitation in another PR

## Test Plan

Update snapshots

### CODE REVIEW

**Comment by victor-teles** [comment]
@biomejs/core-contributors For some reason i have exact match in playground but the snapshot diff fails.

CleanShot 2023-11-17 at 17 10 25

**Comment by ematipico** [comment]
@victor-teles can you point us to the prettier implementation? We usually check their source code, to make sure we match their logic.

One more thing, checking the formatted content doesn't help sometimes. You should check the emitted IR.

**Comment by victor-teles** [comment]
@ematipico I think prettier don't have a comment handling specific for "array hole". (Maybe I need to do some more research)

I think my solution can be simplified if I can get the `get_lines_before` method to work for the `JsArrayHole` node.
At the moment, it's not working because `JsArrayHole` has no tokens and leading leading_trivia, Which is used to determine the number of lines.

With it working, I could just keep the following change: [crates/biome_js_formatter/src/comments.rs](https://github.com/biomejs/biome/pull/756/files#diff-76cdd33c61df8724af782e03fb31985ee10799d8c0adb0c72c239ad69d19cb24)

**Comment by ematipico** [comment]
This is where Prettier handles comments https://github.com/prettier/prettier/blob/main/src/language-js/comments/handle-comments.js

**Comment by victor-teles** [comment]
@ematipico But they don't handle array holes in that file like biome does

**Comment by ematipico** [comment]
Thank you for flagging this. You can use  https://github.com/biomejs/biome/issues/739 to track our divergence, in case you think we should

**Pull request merged**
