### PR TITLE
chore(ci): add update contributors workflow

### PR DESCRIPTION
**Pull request by Sec-ant**
## Summary

Add a workflow to update contributors regularly. This workflow will create a PR to update the contributors list in `Community.astro` and `Contributors.astro`.

If the list doesn't need to be updated, this workflow will not create a PR.

This workflow can also be executed manually.

## Test Plan

Tested on my forked repo.

### CODE REVIEW

**Review by ematipico — APPROVED** [review]
Awesome 😎

**Comment by Sec-ant** [comment]
image

@ematipico This workflow requires a permission in repo settings/actions, I don't have enough permission to enable it:

image

**Comment by ematipico** [comment]
That should work now

**Comment by Sec-ant** [comment]
> That should work now

Still not working: https://github.com/biomejs/biome/actions/runs/8587073115/job/23530928766#step:6:123

I think this is the reason: https://stackoverflow.com/a/73155199

**Comment by ematipico** [comment]
Try now

**Comment by Sec-ant** [comment]
> Try now

Same error: https://github.com/biomejs/biome/actions/runs/8587641956/job/23531549529#step:6:123

**Comment by Conaclos** [comment]
This should be fixed.

**Pull request merged**
