### PR TITLE
feat(lint): support literal names for `useSortedClasses`

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

Part of #1274 

It adds support for object member properties. 

## Test Plan

Updated the current snapshots

### CODE REVIEW

**Review by DaniGuardiola — APPROVED** [review]
Looks good, why the formatting changes on tests though? It makes it a bit hard to review due to the noise.

**Comment by DaniGuardiola** [comment]
Btw, have you considered the cases around template literals with "holes"? What happens in those cases? E.g.

```ts
tw`p-4 m-2 ${something} block absolute`
```

**Comment by ematipico** [comment]
> Btw, have you considered the cases around template literals with "holes"? What happens in those cases? E.g.
> 
> ```ts
> tw`p-4 m-2 ${something} block absolute`
> ```

I have yet to see test cases like this, so I haven't handled them. What do you think? I think we aren't in a position to suggest a fix, because we don't know that `something` is.

**Comment by ematipico** [comment]
> Looks good, why the formatting changes on tests though? It makes it a bit hard to review due to the noise.

My silly editor... 😅 I'll revert them

**Pull request merged**
