### PR TITLE
release: v1.8.0

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

Promoted rules 

- [useImportRestrictions](https://biomejs.dev/linter/rules/use-import-restrictions/)
- [noNodejsModules](https://biomejs.dev/linter/rules/no-nodejs-modules/)
- [useArrayLiterals](https://biomejs.dev/linter/rules/use-array-literals/)
- [noConstantMathMinMaxClamp](https://biomejs.dev/linter/rules/no-constant-math-min-max-clamp/)
- [noFlatMapIdentity](https://biomejs.dev/linter/rules/no-flat-map-identity/)

## Test Plan

CI should work

### CODE REVIEW

**Review by anonrig — APPROVED** [review]

**Comment by Conaclos** [comment]
Do you think that [useImportRestrictions](https://biomejs.dev/linter/rules/use-import-restrictions/) is really mature? We recently introduced a new option, and it is not documented yet. Also, I have the impression that the rule is missing some long-term vision.

**Comment by ematipico** [comment]
We did? Why wasn't that documented? 

I promoted the rules because it's been there for quite some time, and it's been used already by other projects

**Comment by Conaclos** [comment]
Oh actually it is not merged yet: #2977

However, the rule has already an option under another form and is undocumented.
I think we should delay the stabilization of the rule.

**Comment by arendjr** [comment]
To add to the objections for that specific, it's also quite confusing we have both `noRestrictedImports` and `useImportRestrictions`. The PR @Conaclos linked is actually for the former.

**Review by arendjr — APPROVED** [review]
Otherwise looks good :+1:

**Review by anonrig — APPROVED** [review]

**Comment by ematipico** [comment]
Commit [`2171ff8` (#3033)](https://github.com/biomejs/biome/pull/3033/commits/2171ff8637c5a669ff6ac735302a0fe53baa4db7) downgrades `useImportRestrictions`

**Review by denbezrukov — APPROVED** [review]

**Pull request merged**
