### PR TITLE
fix(configuration): `extends` resolution strategy

### LINKED ISSUE #2231: 🐛 Providing `--config-path` changes cwd for `"extends"` module resolving
### Environment information

```block
CLI:
  Version:                      1.6.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v21.6.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       unset

Workspace:
  Open Documents:               0
```

### What happened?

1. Create a config file in a different from cwd location e.g. `config/biome.json`
2. Add config content with the usage of `"extends"` utilizing package module resolving e.g.
```json
{
  "extends": ["@domin-mnd/config/biome"]
}
```
3. Run `biome lint . --config-path config`
4. image

> [!NOTE]
> [MRE CBS](https://codesandbox.io/p/sandbox/runtime-microservice-ygrpgx)

### Expected result

Resolve module from the working directory location where `biome lint` is executed

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by Sec-ant**
## Summary

Fix the resolution strategy of `extends` so it can work as most users would expect in both LSP and CLI:

  - Absolute paths:
    - As is.
  - Relative paths:
    - Resolve the extend configuration file relative to the directory where the current configuration file is.
  - External modules:
    1. First resolve the extend configuration file from the directory where the current configuration file is;
    2. Fallback to resolve the extend configuration file from the working directory.

This also fixes a regression introduced in #2160.

I also updated a few configuration resolution diagnostics and schema comments to provide clearer messages for users.

Closes #2231.

## Test Plan

CI should pass. We cannot test module resolution atm. I tested the behavior locally.

### CODE REVIEW

**Comment by Conaclos** [comment]
> External modules:
> [...]
> Fallback to resolve the extend configuration file from the working directory.

COuld you explain the rationale behind this fallback?

**Comment by Sec-ant** [comment]
> Could you explain the rationale behind this fallback?

1. Before #2160, every external module was resolved from the working directory. So I regard it as a regression of #2160.
2. As #2231 suggests, some users would expect `biome lint . --config-path ./config` to resolve `extends` modules from `cwd` instead of the directory `./config`. This helps to organize config files in another dedicated directory where no `package.json` or `node_modules` are required just for module resolution.

**Comment by ematipico** [comment]
It's worth updating the website too, explain this new resolution and maybe provide an example: https://biomejs.dev/guides/how-biome-works/#configuration-file-resolution

**Comment by Conaclos** [comment]
> 1. Before [fix(lsp): correctly resolve `extends` configs #2160](https://github.com/biomejs/biome/pull/2160), every external module was resolved from the working directory. So I regard it as a regression of [fix(lsp): correctly resolve `extends` configs #2160](https://github.com/biomejs/biome/pull/2160).
>  2. As [🐛 Providing `--config-path` changes cwd for `"extends"` module resolving #2231](https://github.com/biomejs/biome/issues/2231) suggests, some users would expect `biome lint . --config-path ./config` to resolve `extends` modules from `cwd` instead of the directory `./config`. This helps to organize config files in another dedicated directory where no `package.json` or `node_modules` are required just for module resolution.

I can see the interest of this for importing an external module. However, I find this very confusing/dirty for relative paths. Do you think it might make sense to exclude relative paths from this fallback?

**Comment by Sec-ant** [comment]
@Conaclos There's no fallback for relative paths. The fallback is only for external module resolution.

**Comment by Conaclos** [comment]
> @Conaclos There's no fallback for relative paths. The fallback is only for external module resolution.

Thanks for the clarification. LGTM

**Comment by Sec-ant** [comment]
emmm I start thinking this might not be the desired fix.

The website says explicitly that module resolution from the working directory is the desired behavior. But the real problem is that for LSP, the working directory is not necessarily the project root.

image

I don't know cases of other editors, but if Biome LSP is invoked via the VSCode extension, the working directory is where the VSCode executable is (acquired from `std::env::current_dir`). I thought this wasn't fixable so I changed the resolution directory to the configuration dir in #2160. But now I think maybe that's simply wrong.

Can I have some help on how to correctly determine the project root when biome is used with VSCode or other editors?

**Comment by Sec-ant** [comment]
Sorry about this, but I'd like to fix this in a proper way in a following PR. Thank you for your time.

**Pull request closed without merging**
