### PR TITLE
chore: translate README.md to Hindi

### PR DESCRIPTION
**Pull request by harshrathod50**
## Summary

Translated @biomejs/biome package's 'README.md' file to Hindi.

## Test Plan

Not applicable.

### CODE REVIEW

**Review by ematipico — APPROVED** [review]
Thank you!

**Comment by netroy** [comment]
I was quite delighted to see that a major project like this had a Hindi readme, but after I started reading the content, I can't shake off the feeling that this is LLM slop. 
Lot's of very bookish word, very inefficiently communicating what a readme is supposed to communicate.
Despite being a native speaker, I find this readme very difficult to follow because of the choice of words, and grammatical structures.

@harshrathod50 Did you use an LLM to generate this? if yes, which one? Maybe we can try another LLM to regenerate this, and use more every-day language this time. 
and Maybe this time we can have some native speakers provide feedback.
There is no point in having a Hindi readme, if even native speakers can't understand it.

**Comment by harshrathod50** [comment]
Hi @netroy, No LLM was used. I have translated each and every sentence to semantically give the same meaning as it's English counterpart. If you want a simpler version then you are always welcome to translate it to **Simple Hindi** and push it in a new file `README.simple.hi.md`.

Why complain when you can instead contribute? 🙂

**Comment by netroy** [comment]
> Why complain when you can instead contribute? 🙂

Obviously, I'd like to contribute wherever I can. You can see on my profile that contributing is something I quite actively like to do.
But in this case I need to first check with original author to get more context, as to why the language used feels so complicated.

I've personally never used phrases like "प्रदर्शनकारी उपकरण-श्रृंखला", "उद्देश्य उक्त परियोजना", "परियोजना दर्शनशास्र" etc either in my day to day life, or when talking to other Hindi speaking devs. 
To me, the language used here feels like it's meant to discourage most native speakers, unless they also spent quite a lot of time also learning Sanskritized Hindi at an academic level, since the words used here aren't really used in common speech.

Is this really your preferred choice of words to introduce new users to a project like this?
**I'm not personally criticizing you here**. and, if it feels like that, then I'd like to apologize.
If you say that this is how you speak, and this is how you expect other native speakers to communicate, then I'll accept that as a valid opinion.
I just needed to check. Maybe my circle of native speakers just have terrible vocabulary 🤷🏽 .

**Comment by netroy** [comment]
Just out of curiosity I ran this text through multiple "AI generated text" detectors, and they all came back positive. 
**I do not know if that's actually the case here**, since those scanners are known to be occasionally unreliable, but I had to check for my own sanity, because I have never met anyone who writes like this.

I've spent some time at सम्पूर्णानन्द संस्कृत विश्वविद्यालय, and I occasionally even write code in देवनागरी to test if languages and runtimes support unicode properly, and this text sounds too Sanskritized even for me.

आम लोग ना इस तरह से लिखते हैं, और ना इस तरह से बोलते हैं। 
अगर इस फ़ाइल का उद्देश्य है कि हिंदी बोलने वाले लोग भी इस टूल का उपयोग कर सकें, तो फिर हमें ये फ़ाइल फिर से ठीक से लिखनी होगी। पर अगर मकसद सिर्फ नाम के लिए हिंदी Readme बनाना था, तो फिर सब ठीक ही है। You can ignore this conversation.
🙏🏽

**Pull request merged**
