### PR TITLE
feat(grit): complete formatting of all nodes

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

This PR completes the formatting of grit, using straightforward logic. We will improve the formatting as we go, and as we identify possible code that could be improved

Comments aren't appropriately handled yet in the sense that we don't have specific logic about their placement in certain conditions. 

I also renamed the node `GritCurlyPredicateList` to `GritPredicateCurly`. The node **wasn't** a list, and I renamed it following the internal convention. 

## Test Plan

I updated the snapshots. I couldn't find the code for the newly formatted nodes.

### CODE REVIEW

**Review by arendjr — APPROVED** [review]
Really nice!

Maybe you can do a small announcement on it as well when you merge ;)

**Comment by dyc3** [comment]
I would make sure it's available in the playground before making an announcement so people can try it out.

**Comment by ematipico** [comment]
> I would make sure it's available in the playground before making an announcement so people can try it out.

I still need to understand why it currently fails 🤔 weird

**Comment by ematipico** [comment]
> Really nice!
> 
> Maybe you can do a small announcement on it as well when you merge ;)

Not yet, there are still things missing :)

**Pull request merged**
