### PR TITLE
chore: remove superflues diagnostics during traversal

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

This PR removes a superfluous diagnostic from the CLI.

## Test Plan

Diagnostics updated

### CODE REVIEW

**Review by Conaclos — APPROVED** [review]

**Comment by Conaclos** [comment]
It could be nice of adding a changelog entry :)

**Comment by ematipico** [comment]
> It could be nice of adding a changelog entry :)

I'm not sure what to add to be honest. Any help?

**Comment by Conaclos** [comment]
We could just say that Biome no longer emit a superfluous diagnostic and give an example pf a such diagnostic.

**Review by arendjr — APPROVED** [review]
Nice quality of life improvements!

**Pull request merged**
