### PR TITLE
docs(website): Add copy button for commands

### PR DESCRIPTION
**Pull request by eyubkh**
## Summary

I have found my self selecting the commands with the mouse and it will be nice to have a button to copy straight away the command.  

## Test Plan

Before: 
Screenshot 2024-02-10 at 14 05 56

After:
Screenshot 2024-02-10 at 14 06 30

https://github.com/biomejs/biome/assets/66533853/242d2fdd-8161-40fa-bd17-9dfeeb466abe

### CODE REVIEW

**Comment by ematipico** [comment]
The icon is visible for commands that don't overflow. But if the command line overflows, it's barely visible

**Comment by eyubkh** [comment]
Oh my bad 😓, I have fix it and also resized the icon 32px to 20px (I think it looks better).

before: 
old icon

after:
Screenshot 2024-02-10 at 18 05 41

**Comment by ematipico** [comment]
Just a suggestion: have you considered borrowing the styles from starlight/expressive-code? 

From what I can tell, their icon is bigger on mobile, and it seems it's placed in absolute position, so you don't need to scroll horizontally in order to copy the code

**Comment by ematipico** [comment]
Or another suggestion: use the starlight tab component to switch package manager (with the appropriate styles) and use expressive-code code block

**Comment by eyubkh** [comment]
That it a good idea, they have two components to use Tabs and TabItem, I have two questions.  

The text "Copied!" should be translated depending on the language?
Tabs components doesn't have an icon, should I use it without icons or should I modify the Tabs component to integrate icons?

**Comment by ematipico** [comment]
Ideally, if possible, we'd want to have an icon too. 

Anyway, I think we can merge this PR and then follow up with the enhancement, if the components allow us to do so

**Comment by eyubkh** [comment]
Oh great 🎉 , I'm working on it right now to implement the same style like in Astro and Starlight website. On Starlight docs says that is a components that can be use it for that but I cannot make it working.

I will work on that on the following days and open a new pull request when I will have it.  

Thanks @ematipico for merging the pull request 🙌🏽

**Pull request merged**
