### PR TITLE
fix: enable JSX parsing inside `.vue` files

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

Closes https://github.com/biomejs/biome/issues/3464

## Test Plan

I would like to add a test, but I couldn't find a file on the web

### CODE REVIEW

**Comment by minht11** [comment]
Vue supports jsx when lang attribute set as such `lang=jsx` without it, parser error is thrown, [see](https://play.vuejs.org/#__PROD__eNp9kTFPwzAQhf+KdRNIVTLAVKWVAHWAARAwerGSI7g4tmWfQ6Qq/52zo5YOqEsUv++98zv5AHfeV2NCWENDOHijCLfSCtF0etw2df5K29RnjI+xDdqTiEjJC6Nsv5FAUQLT1tlIQolNmSDqEsiiM1gZ11+p6zxvmcAQVpxk/qn7ah+d5SKHfL+E1g1eGwwvnjTnJaxFIZkpY9zPU9EoJFwd9fYL2+9/9H2csibhNWDEMKKEEyMVeqQF796fceL/Exxclwy7L8A35N1S7rjY7pPtuPaZr7R9HLwLpG3/EXcToY3HpXLR7JyLXwK/xsOF1f/q3lS3JSftDPMv8TSW/Q==)

Should we also enable it based on attribute?

**Comment by ematipico** [comment]
> Vue supports jsx when lang attribute set as such `lang=jsx` without it, parser error is thrown, [see](https://play.vuejs.org/#__PROD__eNp9kTFPwzAQhf+KdRNIVTLAVKWVAHWAARAwerGSI7g4tmWfQ6Qq/52zo5YOqEsUv++98zv5AHfeV2NCWENDOHijCLfSCtF0etw2df5K29RnjI+xDdqTiEjJC6Nsv5FAUQLT1tlIQolNmSDqEsiiM1gZ11+p6zxvmcAQVpxk/qn7ah+d5SKHfL+E1g1eGwwvnjTnJaxFIZkpY9zPU9EoJFwd9fYL2+9/9H2csibhNWDEMKKEEyMVeqQF796fceL/Exxclwy7L8A35N1S7rjY7pPtuPaZr7R9HLwLpG3/EXcToY3HpXLR7JyLXwK/xsOF1f/q3lS3JSftDPMv8TSW/Q==)
> 
> Should we also enable it based on attribute?

I believe the original issue comes from a V2 Vue component, but I'm not sure. I'm waiting for OP to share their whole code

**Review by Conaclos — APPROVED** [review]

**Comment by minht11** [comment]
The problem enabling jsx on every vue file would that valid TS code like `const fn = <T>() => {}` would no longer be parsed correctly.

**Review by anonrig — APPROVED** [review]

**Comment by ematipico** [comment]
> The problem enabling jsx on every vue file would that valid TS code like `const fn = <T>() => {}` would no longer be parsed correctly.

Wouldn't users need to add `lang=ts` in their `<script>` tag in order to do so?

**Comment by minht11** [comment]
Sorry if I am wrong, doesn't this PR changes behavior that `lang='ts'` is being parsed as `tsx` and `lang=js` as `jsx`?

**Comment by ematipico** [comment]
Ooooh, I see your point now! I'll fix it later

**Comment by dyc3** [comment]
https://github.com/vuetifyjs/vuetify uses jsx/tsx a bunch, you could use those for tests

**Pull request merged**
