### PR TITLE
docs(noRestrictedImports): update version notice

### PR DESCRIPTION
**Pull request by MaxtuneLee**
## Summary

Changed the version number from `v1.6.0` to `v2.0.0` to reflect the correct introduction version of the no-restricted-imports rule.

Issue mentioned in https://github.com/biomejs/biome/issues/4750

### CODE REVIEW

**Review by dyc3 — DISMISSED** [review]
This doesn't look right. The _options_ have changed in 2.0. The rule has been there since 1.6.0.

**Comment by MaxtuneLee** [comment]
> This doesn't look right. The _options_ have changed in 2.0. The rule has been there since 1.6.0.

Thank you for the review. I reviewed [this pull request](https://github.com/biomejs/biome/pull/1723) and am wondering how users can access configuration documentation for previous versions. Do we need to retain the old docs here, considering that v2 hasn't been released yet?

**Comment by dyc3** [comment]
Yes, we should probably retain the old docs. Go ahead and add them alongside the new docs here in the rule, and make sure to label it with the version it applies to.

**Review by ematipico — APPROVED** [review]
Thank you!

**Pull request merged**
