### PR TITLE
feat(lint/noDuplicateImports): add rule

### PR DESCRIPTION
**Pull request by anonrig**
Work-in-progress.

### CODE REVIEW

**Comment by arendjr** [comment]
Doesn’t our `organizeImports` feature already deduplicate them? Does it make sense to reimplement similar functionality in the linter too?

**Comment by ematipico** [comment]
> Doesn’t our `organizeImports` feature already deduplicate them? Does it make sense to reimplement similar functionality in the linter too?

No, it doesn't.

**Comment by ematipico** [comment]
@anonrig what's the status of the PR?

**Comment by ematipico** [comment]
Close it for now. Feel free to open it once you have some updates.

**Comment by anonrig** [comment]
I'm working on it but not close to finish yet. @ematipico

**Comment by ematipico** [comment]
Please open an issue to track it and assign it to yourself. It's easier to track the progress

**Pull request closed without merging**
