### PR TITLE
feat(biome_js_parser): support RegExp v flag

### LINKED ISSUE #613: 📎 js_parser: support RegExp `v` flag
### Description

Make the JavaScript parser to recognize the RegExp `v` flag (Unicode sets). The [tc39/proposal-regexp-v-flag](https://github.com/tc39/proposal-regexp-v-flag) has reached the stage 4 of the TC39 process and is [widely supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicodeSets#browser_compatibility) by browsers and Node.js/Deno.

For example, the following is currently a parse error:

```js
/[\p{Control}--[\t\n]]/v
```

[Open in playground](https://biomejs.dev/playground/?code=LwBbAFwAcAB7AEMAbwBuAHQAcgBvAGwAfQAtAC0AWwBcAHQAXABuAF0AXQAvAHYA)

### PR DESCRIPTION
**Pull request by nissy-dev**
## Summary

Fix #613

## Test Plan

I add parser test for v flag

### CODE REVIEW

**Review by ematipico — APPROVED** [review]

**Comment by Conaclos** [comment]
Did you take a look to the coverage regressions? Were they expected?

**Comment by nissy-dev** [comment]
Yes. These regression is related to regex syntax. Our parser doesn't check the detail of regex syntax

**Comment by valtlai** [comment]
The `u` and `v` flags are exclusive: a regexp can’t have both, so `/./uv` is should trigger a parse error. I’m not sure if it’s intentional that the parser is more relaxed than the spec here. Because the parser doesn’t allow duplicate regexp flags either, I would consider allowing conflicting flags a bug.

**Comment by nissy-dev** [comment]
> The u and v flags are [exclusive](https://tc39.es/ecma262/#sec-parsepattern): a regexp can’t have both, so /./uv is should trigger a parse error.

Thanks! I didn't realize that. I will submit the follow-up PR

**Pull request merged**
