### PR TITLE
feat(biome_js_analyze): useSemanticElements

### PR DESCRIPTION
**Pull request by isnakode**
## Summary

this PR add `useSemanticElements` lint support #2614 

## Test Plan

insta test

### CODE REVIEW

**Comment by togami2864** [comment]
I think you could make the rule name clearer, like `useSemanticTagsOverRoles`

**Comment by isnakode** [comment]
> I think you could make the rule name clearer, like `useSemanticTagsOverRoles`

sure, how to rename it?, does change directory name enough?

**Comment by togami2864** [comment]
@isnakode  Actually, I don't know the right way, but the following will work.

1. Create a new rule.
2. Copy the logic from the old rule to the new one.
3. Remove references to the old rule in nursery.rs and options.rs.
4. Delete the old rule's files.
5. Execute `just gen-lint` .

**Comment by ematipico** [comment]
Why was this PR closed? The wasn't any need, you could have asked for help :(

**Comment by isnakode** [comment]
> Why was this PR closed? The wasn't any need, you could have asked for help :(

oh, sorry, my laptop is being repaired right now, maybe for 2 weeks (maybe longer), so i decided to close the PR so other people can working on it 😄

**Pull request closed without merging**
