### PR TITLE
refactor: remove the `all` option 

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

Closes https://github.com/biomejs/biome/issues/4663

Unfortunately, there's no migration path other than removing the option.

## Test Plan

Removed all snapshots and tests that were using the option.

### CODE REVIEW

**Review by chansuke — APPROVED** [review]
lgtm

**Comment by ematipico** [comment]
> I agree with removing the top-level `all` property, but is it necessary to remove it for all categories as well? If so, what will be the replacement for enabling a category?

To enable a group, a user will be able to assign `true` to the entire group e.g. `"style": true`.

While this _will_ be possible, we should discourage its usage because it has the same pitfalls of the previous logic

**Comment by arendjr** [comment]
Makes perfect sense! Is the plan still on to have environment groups or whatever we end up calling them? Something like `"react": true` should be valid and not have conflicting rules within its group, I think.

**Review by arendjr — APPROVED** [review]

**Comment by ematipico** [comment]
Yes that's the plan. The proposed name for this concept was "domains"

**Review by fireairforce — APPROVED** [review]
lgtm

**Pull request merged**
