### PR TITLE
fix(formatter): escape double quotes when printing formatter IR

### LINKED ISSUE #1056: 🐛 Quotes within quotes of Formatter IR isn't escaped
### Environment information

```block
This is running Biomejs playground with no special options enabled.
```

### What happened?

1. Had a string in Biome.js playground: https://biomejs.dev/playground/?code=YQB3AGEAaQB0ACAAIgBhACIAIAA%3D
```ts
await "a" 
```
3. Double quotes is not escaped or enclosing string is not single quoted (as in Prettier Formatter IR):
Screenshot 2023-12-04 at 7 53 08 PM
4. This also causes broken syntax highlighting

### Expected result

Expected result is either the double quotes surrounding `"a"` are escaped:

```ts
["await \"a\";", hard_line_break]
```

Or single quotes used for enclosing quotes instead:

```ts
['await "a";', hard_line_break]
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by dyc3**
## Summary

Double quotes in source code when printing formatter IR were previously not escaped, causing poor syntax highlighing on the playground. This PR escapes quotes with a simple string replacement.

fixes #1056

## Test Plan

CI should pass, ~~but I'm not sure where to add a test for this.~~ I've added a unit test for this.

### CODE REVIEW

**Review by ah-yu — COMMENTED** [review]
> CI should pass, but I'm not sure where to add a test for this.

Maybe you can refer to this test
https://github.com/biomejs/biome/blob/312e46f269d565a3f8b2b72a312da8f9a90c5fa7/crates/biome_formatter/src/format_element/document.rs#L718-L752

**Comment by dyc3** [comment]
Done. I've added a unit test for this. Thanks for the code pointer @ah-yu

**Review by ematipico — APPROVED** [review]
Awesome work @dyc3 !

**Review by ah-yu — APPROVED** [review]
Thank you!

**Pull request merged**
