### PR TITLE
refactor: don't check dir and symlink against include

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

In #1687, I fixed a bug where directories were traversed even if they were ignored.
Unfortunately this introduced a new bug: any folder that doesn't match at least one pattern in `include` are rejected.
For example, given the following config

```js
{ files: { include: ["./**/*.js"] } }
```

And running `biome format .` results in no processed files because `.` doesn't match `./**/*.js`.

To fix this issue, we should handle directories differently:
If a directory match a prefix of a pattern, then it matches the pattern.
This change is not trivial because our current glob library don't support such mode.

Reverting #1687 seems undesirable.

As temporary workaround, I propose to consider that directories always match any pattern of `include`. In other words, we skip `include` checking when the path is a directory.
We retain most of the intention of #1687 because we can still ignore entire directories using `ignore`.

EDIT: we also skip symlinks that target a directory.

EDIT: the second commit fixes a bug I found: the virtual path of a symlink that targets to a directory was erroneously computed. For example if `foo` is a symbolic link to `bar`, the computed path was `foo/bar`, while it should be `foo`.

EDIT: the last commit fixes another bug related to symlink: if `foo` is a symbolic link to `bar`, that contains `sub/file.js`, the virtual path was computed as `foo/file.js` instead of `foo/sub/file.js`.

## Test Plan

I added some tests.

### CODE REVIEW

**Review by anonrig — APPROVED** [review]

**Comment by ematipico** [comment]
I'm concerned by the fact that we are adding a lot of assumptions without documenting anything. Or without suggesting a clear path forward.

I'm not fond of this patch, and I would prefer to revert the previous change, and limit that change to only symbolic links. After all, nobody filed any issues so far, so I don't see any particular harm.

Practically, take a step back, and move more carefully.

**Comment by arendjr** [comment]
> I'm not fond of this patch, and I would prefer to revert the previous change, and limit that change to only symbolic links. After all, nobody filed any issues so far, so I don't see any particular harm.

In that case I would have to file an issue :sweat_smile: Traversing ignored directories runs into issues when those directories contain inaccessible files for whatever reason.

**Comment by Conaclos** [comment]
> I’m not too excited about assuming that symlinks point to directories. I have a project where that’s not the case 😅 Can’t we check whether the destination is a directory and base the decision on that?

Fixed :) I found another bug around path computation. See the PR description (`EDIT`).

> I'm concerned by the fact that we are adding a lot of assumptions without documenting anything. Or without suggesting a clear path forward.

I updated the changelog entry.
I think it is a fair patch. This is a partial revert of #1687.
While this is not perfect, it avoids many file system errors by actually skipping directories that are ignored in `ignore`.

**Review by ematipico — APPROVED** [review]
I tested the fix on a couple of real projects and they seem to work. I'm happy to merge it.

@Conaclos could you please create a task for us to follow up on this?

**Pull request merged**
