### PR TITLE
docs: fix the broken link in analyzer/index.mdx

### PR DESCRIPTION
**Pull request by ganta**
## Summary

The link to the "Import Sorting" page in `docs/{ja,zh-cn,pt-br}/analyzer/index.mdx` is broken.

## Test Plan

Ensure that the link is working.

### CODE REVIEW

**Comment by Conaclos** [comment]
I think this affects also other language. Would you like to fix them as well?

**Comment by ganta** [comment]
Since I am here, I will fix the other languages as well 👌🏼

**Comment by ganta** [comment]
I have fixed it in all languages 🙌🏼

**Comment by Conaclos** [comment]
Great! Thanks!

**Pull request merged**
