### PR TITLE
feat(graphql_formatter): bootstrap GraphQL formatter

### PR DESCRIPTION
**Pull request by denbezrukov**
## Summary

This PR bootstraps all of the infrastructure for biome_graphql_formatter, including:

- the biome_graphql_formatter crate itself
- configuration through biome_cli
- configuration through biome_service

## Test Plan

cargo test

### CODE REVIEW

**Review by ematipico — APPROVED** [review]
Great job here! Are we ready to merge it? I haven't seen reports for concerning bugs that would require a 1.8.3 release.

**Review by ematipico — CHANGES_REQUESTED** [review]
It seems you didn't create the new crates using `just new-crate`. Can you update `knope.toml` to add the new crates?

**Comment by denbezrukov** [comment]
> Great job here! Are we ready to merge it? I haven't seen reports for concerning bugs that would require a 1.8.3 release.

I think so. I know only some fixes for css. https://github.com/biomejs/biome/pull/3251 https://github.com/biomejs/biome/pull/3257 https://github.com/biomejs/biome/pull/3254
If we have to release something, the formatter is disabled by default, and IDEs require an update to support formatting.

**Comment by ematipico** [comment]
> > Great job here! Are we ready to merge it? I haven't seen reports for concerning bugs that would require a 1.8.3 release.
> 
> I think so. I know only some fixes for css. #3251 #3257 #3254 If we have to release something, the formatter is disabled by default, and IDEs require an update to support formatting.

Then we should at least hide all the CLI options, so we can safely merge this PR. Or we can wait a little bit until we ship a new patch release

**Review by arendjr — APPROVED** [review]
Nice job! Agreed we may want to hide the CLI options until the formatter is ready, other than that, looks good :+1:

**Comment by denbezrukov** [comment]
@ematipico Could we merge it?

**Review by ematipico — APPROVED** [review]

**Pull request merged**
