### PR TITLE
feat: add musl target support in npm pakcage

### PR DESCRIPTION
**Pull request by matteosacchetto**
## Summary
In this PR i am adding support for the linux musl target in the npm package `@biomejs/biome`. 
The idea of adding this feature was initially introduced in discussion #946, since from version 1.40 biome is now built also for the linux musl target thanks to PR #821.

In this PR i am modifying the following files:
- `generate-packages.mjs`: to add the generation of the packages also for linux-musl and add libc field to package.json (reference issue: https://github.com/pnpm/pnpm/issues/4454)
- `postinstall.js`: to identify if on linux-musl and select the correct package
  -  the `isMusl` function was implemented as suggested in #946 following the implementation of microsoft/vscode-ripgrep#25, with the only difference that I used the sync version of exec.
- `biome/bin/biome`: add linux-musl detection

Minore issue, though I do not know if it is solvable, on linux with npm it will install both `@biomejs/cli-linux-${arch}` and `@biomejs/cli-linux-${arch}-musl`, since npm will install based on arch and platform (which is `linux` for both packages).

## Test Plan
I tested the `isMusl()` function on both linux and alpine to check it was working properly.
I checked that `getName()` was returning the correct names for the various platforms and arch.

I tested locally, by running `npm pack` and installing them locally and on alpine, the correct musl target is run.
Tested also with `bun` on alpine, and with `pnpm`.

### CODE REVIEW

**Comment by ematipico** [comment]
> Minore issue, though I do not know if it is solvable, on linux with npm it will install both @biomejs/cli-linux-${arch} and @biomejs/cli-linux-${arch}-musl, since npm will install based on arch and platform (which is linux for both packages).

This is something we could add to our documentation, what do you think? Maybe here: https://biomejs.dev/guides/manual-installation/#supported-platforms

**Comment by matteosacchetto** [comment]
> > Minore issue, though I do not know if it is solvable, on linux with npm it will install both @biomejs/cli-linux-${arch} and @biomejs/cli-linux-${arch}-musl, since npm will install based on arch and platform (which is linux for both packages).
> 
> This is something we could add to our documentation, what do you think? Maybe here: https://biomejs.dev/guides/manual-installation/#supported-platforms

I agree that it should be something to mention, though I do not know where we could mention it.
I feel like the "manual installation" section is not 100% the correct place, since it is something related to when it is installed with NPM

**Comment by ematipico** [comment]
We could add a new heading `###` after the installation instructions: https://biomejs.dev/guides/getting-started/#installation

**Comment by ematipico** [comment]
Going to merge this, we can write the documentation in a different PR :D

**Pull request merged**
