### PR TITLE
feat(workspace): make types camel case

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

Closes https://github.com/biomejs/biome/issues/4366

All fields are now camel case. 

This will break the playground, which means that we need to update it once `next` is merged to `main`

## Test Plan

I updated the JS APIs, CI should pass.

### CODE REVIEW

**Comment by ematipico** [comment]
> Should we also ensure that option values are in camel case? For now there are in Pascal Case in the playground.

That's what I have been doing with this PR. Are there other options that I missed?

**Comment by Conaclos** [comment]
> That's what I have been doing with this PR. Are there other options that I missed?

I mean the values, not the names. For examples `tabs` instead of `Tabs`. I think we have to change the `Display` implementation?

**Comment by ematipico** [comment]
> > That's what I have been doing with this PR. Are there other options that I missed?
> 
> I mean the values, not the names. For examples `tabs` instead of `Tabs`. I think we have to change the `Display` implementation?

Yes, that's what the PR is for :) so, if you spot something that I missed, please do so!

**Comment by Conaclos** [comment]
Should we not update `Display` implementation such as

https://github.com/biomejs/biome/blob/dc0b3eec7571e8e7d0f2b38ae1c3f3b694a0cbdb/crates/biome_formatter/src/lib.rs#L123-L130

?

**Comment by ematipico** [comment]
The display implementation isn't used in WASM, so we don't need to change it

**Review by Conaclos — APPROVED** [review]

**Pull request merged**
