### PR TITLE
docs(zh-CN): translated sidebar

### PR DESCRIPTION
**Pull request by dufu1991**
## Summary

Partial work from https://github.com/biomejs/biome/issues/1065 that translates the documentation sidebar.

## Test Plan

- Check if the translation matches the correct translation of the terms
- Check if there's missing any translation of the terms

### CODE REVIEW

**Comment by nissy-dev** [comment]
@dufu1991 Can you resolve the conflict?

@zhoujian-official If you are interested in, we would appericiate your review.

**Comment by dufu1991** [comment]
> @dufu1991 Can you resolve the conflict?

The conflict has been resolved.

**Comment by nissy-dev** [comment]
@dufu1991 It seems that there was still a conflict, so I fixed it on my side. However CI failed.

I'm sorry, but could you please apply format to astro.config.ts so that CI can pass? I wanted to do it myself, but I couldn't push to this branch.

**Comment by dufu1991** [comment]
> The conflict has been resolved.

The conflict has been resolved.

**Comment by dufu1991** [comment]
> @dufu1991 It seems that there was still a conflict, so I fixed it on my side. However CI failed.
> 
> I'm sorry, but could you please apply format to astro.config.ts so that CI can pass? I wanted to do it myself, but I couldn't push to this branch.

The conflict has been resolved.

**Comment by nissy-dev** [comment]
@dufu1991 Thanks you!

**Pull request merged**
