### PR TITLE
docs(lint/style/useFilenamingConvention): fix example options

### PR DESCRIPTION
**Pull request by zauni**
## Summary

Just a small change that corrects the example option in the documentation.

### CODE REVIEW

**Comment by arendjr** [comment]
Can you run `just gen-lint` so the generated docs are updated?

**Comment by zauni** [comment]
@arendjr thanks for the heads up 🙂

**Comment by Sec-ant** [comment]
@zauni The markdown doc of this rule is auto generated from the doc comments in the source code. So you'll have to update the comments in the source to reliably update them:

https://github.com/biomejs/biome/blob/bf61fb9ff31154619a5ccc7085b2f0c14988508f/crates/biome_js_analyze/src/lint/style/use_filenaming_convention.rs#L41-L41

And there's also [another option `requireAscii`](https://github.com/biomejs/biome/blob/bf61fb9ff31154619a5ccc7085b2f0c14988508f/crates/biome_js_analyze/src/lint/style/use_filenaming_convention.rs#L57) that is [missing in the example](https://github.com/biomejs/biome/blob/bf61fb9ff31154619a5ccc7085b2f0c14988508f/crates/biome_js_analyze/src/lint/style/use_filenaming_convention.rs#L34), would you mind  updating it as well?

Once you've updated the comments in the source, `just gen-lint` will handle the rest for you.

**Review by arendjr — APPROVED** [review]
Thanks!

**Comment by zauni** [comment]
@arendjr Thanks for the patience 🙂 Also adjusted some code comments after you approved, hope they are okay

**Comment by arendjr** [comment]
No problem, all changes look good :+1:

**Pull request merged**
