### PR TITLE
perf(ci): speedup free disk space action

### PR DESCRIPTION
**Pull request by Jayllyz**
## Summary

`free-disk-space` is useful but quite slow.
A contributor to `rspack` has made a fork which is faster.

I have also tested another version using https://lib.rs/crates/rmz but the installation time makes it slower.

Related PR with the changes : https://github.com/jlumbroso/free-disk-space/pull/26

## Test Plan

Tested on a fork + rspack is also already using it.

### CODE REVIEW

**Comment by nhedger** [comment]
Do we know if the fork will be maintained? If not perhaps we should wait for the PR to get merged.

**Comment by Jayllyz** [comment]
I dont know.

**Comment by Jayllyz** [comment]
I dont know.

**Comment by nhedger** [comment]
> I have also tested another version using https://lib.rs/crates/rmz but the installation time makes it slower.

What's that using cargo install or by downloading the prebuilt binary from GitHub ?

**Comment by Jayllyz** [comment]
> Was that using cargo install or by downloading the prebuilt binary from GitHub ?

`cargo install rmz` + `sudo ln -s /home/runner/.cargo/bin/rmz /usr/local/bin/rmz`

**Comment by ematipico** [comment]
> Do we know if the fork will be maintained? If not perhaps we should wait for the PR to get merged.

Well, the action we use now isn't *that* maintained too (the PR was open almost a month ago). I don't mind using this alternative

**Pull request merged**
