### PR TITLE
feat(formatter): add option `json.formatter.trailingComma`

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

This is a follow up of https://github.com/biomejs/biome/pull/1944

Closes https://github.com/biomejs/biome/issues/926

This PR adds the option `json.formatter.trailingComma`. Its options are the same of `js.formatter.trailingComma`, exception for `es5`, which doesn't have anything to do with JSON.

> [!WARNING]
> This option changes its value if `json.parser.allowTrailingComma` is set to `true`. That was done to have both parser and formatter to behave in the same way.

Let me know what you think about this decision ⬆️ Logically, I thought it made sense, because if a user **wants** to parse JSON trailing commas, and it makes sense to leave them there.

## Test Plan

I added a new test case

### CODE REVIEW

**Comment by ematipico** [comment]
@Sec-ant I'd like your input here. What do you think?

**Comment by Sec-ant** [comment]
Hey, thanks for mentioning. Here are my two cents:

1. **Regarding Naming Conventions:**

   It's essential to maintain a consistent naming style across our configuration options. Given that we use plural forms in options like `javascript.formatter.{semicolons, arrowParentheses, quoteProperties}`, and `json.parser.{allowComments, allowTrailingCommas}`, I recommend we align the naming accordingly. Therefore, `javascript.formatter.trailingComma` should be updated to `javascript.formatter.trailingCommas`, and similarly, we should name the new option `json.formatter.trailingCommas` for consistency.

2. **Concerning the Configuration Options:**

   Initially, I considered three settings: `all`, `none`, and `passthrough` (or a shorter alternative). The `passthrough` option signifies that we leave the trailing commas unchanged, minimizing surprises and unexpected code differences when developers upgrade. However, since the `javascript.formatter.trailingCommas` option does not include a `passthrough` choice, it might be reasonable to limit the options to just `all` or `none`.

   If we decide to support `passthrough`, it should be the default to be as least surprising as possible. If not, considering that [using trailing commas in `jsonc` files is generally discouraged](https://code.visualstudio.com/docs/languages/json#_json-with-comments:~:text=the%20mode%20also%20accepts%20trailing%20commas%2C%20but%20they%20are%20discouraged%20and%20the%20editor%20will%20display%20a%20warning.), setting the default to `none` seems appropriate.

   Furthermore, I believe the default configuration for the `jsonc` language should be as follows to prevent issues mentioned [here](https://github.com/biomejs/biome/pull/1944#issuecomment-1971410554):
   ```json
   {
     "json": {
       "parser": {
         "allowComments": true,
         "allowTrailingCommas": true
       },
       "formatter": {
         "trailingCommas": "none"
       }
     }
   }
   ```

3. **On the Mechanism:**

   I'm uncertain whether we should modify the `json.formatter.trailingCommas` option based on the `json.parser.allowTrailingCommas` setting. My stance is that `json.formatter.trailingCommas` should only be active when `json.parser.allowTrailingCommas` is true. If set to false, this option should be ignored. My understanding is that if `json.parser.allowTrailingCommas` is false and encounters a trailing comma, it should be treated as invalid syntax, resulting in a bogus node. Consequently, the formatter would not detect a trailing comma in such scenarios, treating the bogus node as plain text. Therefore, altering the `json.formatter.trailingCommas` value seems unnecessary.

**Comment by ematipico** [comment]
I applied all the suggestions.

A couple of notes:
- @arendjr a disparity between VSCode and CLI isn't possible at the moment. I mean, we can totally support that, by adding an option coming from the client (VSCode). Still, I have some reservations about the difference between editor and CLI. We can revisit this later
- @Sec-ant A `passthrough` option is definitely something we can evaluate. `rustfmt` does something similar. However, this is a bigger discussion that involves JavaScript too, since they both share the same mechanism

**Review by Sec-ant — COMMENTED** [review]
@ematipico I left a few reviews which I hope wouldn't bother you too much.

And a last question is shouldn't we also update the name of `javascript.formatter.trailingComma` to `javascript.formatter.trailingCommas`? This is certainly a breaking change but now that we decide to use plural forms for every other option, I assume you agree with me right?

**Comment by ematipico** [comment]
Thank you for the review @Sec-ant , I will address them later.

I won't change existing options because they are breaking changes. We can create new options and deprecate the old ones, and eventually remove everything in V2.0

**Pull request merged**
