### PR TITLE
feat(website): Custom Scroll Bar

### PR DESCRIPTION
**Pull request by shoaibkh4n**
## Summary:
Improving the first impression of the website by implementing the logic for custom scroll bar. Default scroll bar just destroy the entire look of the website. Now website is looking more clean.
That's the suggestion PR , depends on person to person but I think it makes the website more cool.

### CODE REVIEW

**Comment by ematipico** [comment]
I opened the link with Chrome, but I can't see any difference in the scroll bar. Do I miss something?

**Comment by shoaibkh4n** [comment]
Hey , Here you can see the clear diff in these pictures.
After:
Screenshot 2024-02-12 224104
Screenshot 2024-02-12 224128

Before:
Screenshot 2024-02-12 224159
Screenshot 2024-02-12 224215

**Comment by ematipico** [comment]
Way better! Thank you !

**Comment by shoaibkh4n** [comment]
Hey @ematipico , I have one more suggestion , Can we just remove the overflow-x and make the text-wrap to pretty, in the code and output box of the home page. I already did this , that's also looks very clean and better. Approve these images and I will open a new PR for this too. 🎉😅. This just drastically makes the website look clean, these scroll bars and the code output boxes just annoys me everytime I opened the website.

After:
Screenshot 2024-02-12 225214,

Before:
Screenshot 2024-02-12 225321

**Pull request merged**
