### PR TITLE
refactor: use rustc-hash

### PR DESCRIPTION
**Pull request by Conaclos**
## Summary

Use `FxHashSet` and `FxHasMap` where possible.
This is a basic tip to ensure efficient computation of hashes.

## Test Plan

Ci should pass. No perf regression should be noticed on benchmarks.

### CODE REVIEW

**Comment by Conaclos** [comment]
!bench_analyzer

**Comment by Conaclos** [comment]
!bench_formatter

**Comment by Conaclos** [comment]
!bench_cli

**Comment by Conaclos** [comment]
!bench_parser

**Review by ematipico — APPROVED** [review]

**Pull request merged**
