### PR TITLE
chore(vscode): switch from `npm` to `pnpm`

### PR DESCRIPTION
**Pull request by nhedger**
## Summary

This PR:

- [x] Replaces `npm` with `pnpm` for managing the dependencies of the VS Code extension.
- [x] Adds the `editors/vscode` folder as a pnpm workspace

Additionally, this PR updates the `package` script so that `vsce` does not attempt to include `node_modules` in the VSIX file. This is required because at the moment `vsce` is not able to resolve dependencies downloaded by `pnpm`. This should not have any effect because we're already bundling the extension with all of its dependencies (`--bundle` is compile script).

## Test Plan

- [x] Run `pnpm build`
- [x] Run `pnpm package`
- [x] Run `pnpm pack:dev`
- [x] Actually run extension and test formatting works

### CODE REVIEW

**Comment by ematipico** [comment]
Does vsce support pnpm now? The main reason we stayed at npm was because pnpm wasn't supported

**Comment by nhedger** [comment]
Since we bundle the extension, it does not matter.

The reason `vsce` does not work with `pnpm` is that it cannot correctly resolve node_modules and include them in the VSIX file, which is not necessary in our case, because the dependencies are bundled in the output file.

**Review by ematipico — APPROVED** [review]

**Comment by ematipico** [comment]
@nhedger we need to update the workflows with pnpm


The release workflow is failing

https://github.com/biomejs/biome/actions/runs/6153342088/job/16697066155#step:13:1

**Comment by nhedger** [comment]
I can take a stab at it later today.

**Comment by nhedger** [comment]
> @nhedger we need to update the workflows with pnpm
> 
> The release workflow is failing
> 
> [biomejs/biome/actions/runs/6153342088/job/16697066155#step:13:1](https://github.com/biomejs/biome/actions/runs/6153342088/job/16697066155#step:13:1)

https://github.com/biomejs/biome/pull/249

**Comment by lppedd** [comment]
> The reason vsce does not work with pnpm is that it cannot correctly resolve node_modules and include them in the VSIX file, which is not necessary in our case because the dependencies are bundled in the output file.

@nhedger not sure if this was explained in the vsce repository discussion, but thanks!  
This made it more clear on why and when we can bypass the issue.

**Pull request merged**
