### PR TITLE
feat(project): show message when a file is protected

### PR DESCRIPTION
**Pull request by ematipico**
## Summary

Closes https://github.com/biomejs/biome/issues/1355

This PR adds the concept of protected files, files that Biome won't process because they are handled by other tools.

I took the chance to add some verbose diagnostic that should provide more information on how to hide of fix the diagnostics.

## Test Plan

Added new snapshot tests

### CODE REVIEW

**Review by haze — APPROVED** [review]
Would it be worthwhile to add a flag to disable this?

**Comment by ematipico** [comment]
> Would it be worthwhile to add a flag to disable this?

That's something we can evaluate, but I think it requires more design and discussion, so it should be tracked in a different task and implemented in a different PR.

**Comment by Conaclos** [comment]
> > Would it be worthwhile to add a flag to disable this?
> 
> That's something we can evaluate, but I think it requires more design and discussion, so it should be tracked in a different task and implemented in a different PR.

Another option is to format the file if it is explicitly listed.
For example:

```shell
biome format --write ./package.json
```
will format `package.json`.

And:

```shell
biome format --write .
```
will not format `package.json`.

**Comment by ematipico** [comment]
That wouldn't work in the LSP

**Pull request merged**
