### PR TITLE
fix: void error on type of a function declaration

### LINKED ISSUE #294: 🐛 noConfusingVoidType flags function type returning void as error
### Environment information

```block
CLI:
  Version:                      1.2.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.16.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/9.8.1"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 true

Workspace:
  Open Documents:               0

Discovering running Biome servers...

Running Biome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

i The client isn't connected to any server but rage discovered this running Biome server.

Server:
  Version:                      1.2.0
  Name:                         biome_lsp
  CPU Architecture:             x86_64
  OS:                           linux

Workspace:
  Open Documents:               0

Other Active Server Workspaces:

Workspace:
  Open Documents:               1
  Client Name:                  Visual Studio Code
  Client Version:               1.82.2
```

### What happened?

Having a typescript function type:

```ts
type FallbackHandler = (error?: Error) => void;
```

Biome flags this as an error:

"void is only valid as a return type or a type argument in generic type biome[lint/nursery/noConfusingVoidType](https://biomejs.dev/linter/rules/no-confusing-void-type)"

### Expected result

Function types returning `void` should be ok.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### PR DESCRIPTION
**Pull request by b4s36t4**
## Summary

Solves issue with raising error on function type.

Fix #294

## Test Plan
Added a new test case in `valid.ts` to verify the functionality is working fine.

### CODE REVIEW

**Review by Conaclos — APPROVED** [review]
Thanks!

**Comment by b4s36t4** [comment]
Thanks ❤. My first PR 😁

**Comment by Conaclos** [comment]
A concise and perfect fix :)

**Comment by atheck** [comment]
Thank you,

**Pull request merged**
