### PR TITLE
refactor(codemod/biome_js_analyze): derive `Applicability` for all lint rule actions

### LINKED ISSUE #2797: ☂️ Analyzer internal refactors
### Description

This PR lists some internal refactors we should apply to our internal analyzer infrastructure. These changes will allow us to minimise the burden of how we write analyser rules and emit better documentation.

- [x] #2798
- [x] #2799
- [x] #2801
- [x] #2800

### LINKED ISSUE #2799: Compute fix kind from metatadata
The `RuleAction` now accepts an `applicability` field, determining whether the action is safe/unsafe. 

However, we also provide the same information to our `RuleMeta`, which is `fix_kind`. 

Once https://github.com/biomejs/biome/issues/2798 is completed, we can retrieve the `fix_kind` using `ctx.metadata().fix_kind`.

The idea is to create a method inside `FixKind` called `into_applicability` that returns `Applicability`. This method should panic (use .`expect()`) if the fix kind isn't provided via macro.

The field `applicability` should become **private** (remove `pub`), however do that at the end. I suggest to create a new method called `new` inside `RuleAction`, and then progressively phase out the manual construction of the struct

```rs
impl RuleAction {
	pub fn new(category: ActionCategory, applicability: Applicability, message: MarkupBuf, mutation: BatchMutation) -> Self {
		Self {
			category,
			applicability,
			message,
			mutation
		}
	}
}
```

As a rule, we should have:

```rs

        Some(JsRuleAction {
            category: ActionCategory::QuickFix,
            applicability: ctx.metadata().to_applicability(),
            message: markup! { "" }.to_owned(),
            mutation,
        })
```

### PR DESCRIPTION
**Pull request by dyc3**
## Summary

Following up on the previous PR, #2885, this changes all the JS rules to derive their applicability from the `FixKind` supplied in the metadata. Should completely resolve #2799.

closes #2799
closes #2797

## Test Plan

Should compile and pass tests.

### CODE REVIEW

**Comment by dyc3** [comment]
To get the tests to pass, I had to change the fix_kind for these rules:
- `useRegexLiterals`
- `useNumberNamespace`
- `noUnusedLabels`
- `noUselessLoneBlockStatements`

All of these appeared to be emitting safe fixes before, so I've updated the fix_kind accordingly.

**Comment by Conaclos** [comment]
Should we implement `Into<Applicability>` for `RuleMetadata`? This could allow removing `to_applicability()` and just pass `ctx.metadata()`. If we keep `to_applicability()`, I could suggest a distinct name. Maybe just `applicability()`.

**Comment by dyc3** [comment]
I don't think so. You're right in that it would reduce some of the boilerplate, but IMO it's inconsequential. To me, the `From` and `Into` traits represent an equivalence relationship between 2 types, and implementing `Into<Applicability>` violates that because it loses the majority of the information.

I do agree with the name change though.

**Comment by Conaclos** [comment]
Fair enough. Let's change the name and merge it :)

**Comment by ematipico** [comment]
> Fair enough. Let's change the name and merge it :)

I suggested `to_applicability` because it follows [rust naming conventions](https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv)

**Comment by Conaclos** [comment]
> I suggested to_applicability because it follows [rust naming conventions](https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv)

I suggested implementing `into` because the `to_` misled me.
But this is not a conversion. So `as_`/`to_`/`into_` doesn't apply here?

**Comment by ematipico** [comment]
Yeah it makes sense, now that I write more of the docs.

`applicability()` makes more sense

**Pull request merged**
