### PR TITLE
docs(ja): update homepage

### PR DESCRIPTION
**Pull request by yayami3**
## Summary

Update Japanese homepage.

Related: https://github.com/biomejs/biome/issues/1958

I referred to this pull request. https://github.com/biomejs/biome/pull/1959

## Test Plan

Run homepage locally and check it.

### CODE REVIEW

**Comment by ematipico** [comment]
Thank you! It seems there are still few bits to translate:

Screenshot 2024-03-04 at 08 57 04
Screenshot 2024-03-04 at 08 57 09
Screenshot 2024-03-04 at 08 57 15

**Comment by yayami3** [comment]
Thank you for your comment and amazing project!

I intentionally do so. Even in Japanese documents, there are cases where English is used, such as in slogans.

**Comment by morinokami** [comment]
@ematipico Personally, I believe it would be beneficial to translate these slogans as well. Firstly, since readers who struggle with English are likely reading the Japanese version, translating these would serve their needs better. Additionally, since the sentence "One toolchain for your web project" at the top of the page has already been translated, it would be better to translate them to be consistent with it.

**Comment by ematipico** [comment]
Thank you @morinokami , feel free to follow up with a PR :)

**Comment by morinokami** [comment]
@ematipico Done! https://github.com/biomejs/biome/pull/1962

**Pull request merged**
