### PR TITLE
feat(lint/noPrototypeBuiltins): add code fix action and cover scenarios from `prefer-object-has-own`

### PR DESCRIPTION
**Pull request by kaioduarte**
## Summary

Closes https://github.com/biomejs/biome/issues/3927

## Test Plan

Snapshots + CI

### CODE REVIEW

**Comment by Conaclos** [comment]
Hi @kaioduarte!

I am sorry I completely missed the fact that we already [noPrototypeBuiltins](have https://biomejs.dev/linter/rules/no-prototype-builtins/) which has some overlap with the rule you are implementing.
ESLint has both [no-prototype-builtins](https://eslint.org/docs/latest/rules/no-prototype-builtins) and [prefer-object-has-own](https://eslint.org/docs/latest/rules/prefer-object-has-own), but in Biome we try to avoid overlapping.

I think we could improve `noPrototypeBuiltins` to include the cases that are not yet covered such as `Object.prototype.hasOwnProperty.call()`. We could also add a code fix as the one you implemented here.
More globally I could even report any read of a prototype builtins (regardless whether it is called or not), e.g `const x = Object.prototype.hasOwnProperty`.
What do you think?

**Comment by kaioduarte** [comment]
Sounds good, I'll take a look at that later. Should I add `prefer-object-has-own` to the rule's sources array?

**Comment by Conaclos** [comment]
> Should I add prefer-object-has-own to the rule's sources array?

Yes. This will avoid thinking that the rule was not covered.

**Comment by kaioduarte** [comment]
I haven't done the read-only part yet, I only incorporated the changes from the other rule while adapting the code fix.

**Review by ematipico — APPROVED** [review]

**Comment by Conaclos** [comment]
LGTM

> I haven't done the read-only part yet, I only incorporated the changes from the other rule while adapting the code fix.

This could be left for another PR.

**Pull request merged**
