### PR TITLE
[WIP]feat(linter): initialize semantic model for css

### PR DESCRIPTION
**Pull request by togami2864**
## Summary
Currently WIP. I'll start by implementing the basic `scope` and `bindings` events."

### CODE REVIEW

**Comment by ematipico** [comment]
Is there the concept of "scope" in CSS? If so, can you provide an example? I am curious

**Comment by chansuke** [comment]
:rocket:

**Comment by togami2864** [comment]
@ematipico 
There are scopes for CSS variables.  e.g https://blog.logrocket.com/css-variables-scoping/
However, they can change depending on the HTML structure like

```
body {
    background: var(--bgColor);
}

div {
    --bgColor: limegreen; // can reference --bgColor because div is child of body. If not, it couldn't reference it.
}

<body>
    <div>Div 1</div>
    <div>Div 2</div>
</body>
```
And with this PR approach, it's not feasible, so I need to rethink things😅

**Comment by togami2864** [comment]
I'll close this since I'm rethinking the model and writing the doc for the discussion now.

**Pull request closed without merging**
